-- Schema for H2 tests (mirrors Liquibase changesets)

CREATE TABLE IF NOT EXISTS CHAT_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EXTERNAL_USER_ID VARCHAR(36) NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    AVATAR_URL VARCHAR(500),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'OFFLINE',
    CUSTOM_STATUS VARCHAR(100),
    LAST_SEEN_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_CHAT_USER_EXT_TENANT UNIQUE (EXTERNAL_USER_ID, TENANT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_CHAT_USER_EXTERNAL_ID ON CHAT_USER (EXTERNAL_USER_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_USER_TENANT ON CHAT_USER (TENANT_ID);

CREATE TABLE IF NOT EXISTS CHAT_CONVERSATION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID VARCHAR(36) NOT NULL,
    PARTICIPANT_ONE_ID BIGINT NOT NULL,
    PARTICIPANT_TWO_ID BIGINT NOT NULL,
    LAST_MESSAGE_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_CONV_PARTICIPANT_ONE FOREIGN KEY (PARTICIPANT_ONE_ID) REFERENCES CHAT_USER (ID),
    CONSTRAINT FK_CHAT_CONV_PARTICIPANT_TWO FOREIGN KEY (PARTICIPANT_TWO_ID) REFERENCES CHAT_USER (ID),
    CONSTRAINT UK_CHAT_CONV_PARTICIPANTS UNIQUE (TENANT_ID, PARTICIPANT_ONE_ID, PARTICIPANT_TWO_ID)
);

CREATE INDEX IF NOT EXISTS IDX_CHAT_CONV_TENANT ON CHAT_CONVERSATION (TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_CONV_PARTICIPANT_ONE ON CHAT_CONVERSATION (PARTICIPANT_ONE_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_CONV_PARTICIPANT_TWO ON CHAT_CONVERSATION (PARTICIPANT_TWO_ID);

CREATE TABLE IF NOT EXISTS CHAT_CHANNEL (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID VARCHAR(36) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    NAME VARCHAR(100),
    SLUG VARCHAR(100),
    DESCRIPTION VARCHAR(500),
    AVATAR_URL VARCHAR(500),
    CREATOR_ID BIGINT NOT NULL,
    IS_ARCHIVED SMALLINT DEFAULT 0,
    LAST_MESSAGE_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_CHANNEL_CREATOR FOREIGN KEY (CREATOR_ID) REFERENCES CHAT_USER (ID),
    CONSTRAINT UK_CHAT_CHANNEL_TENANT_SLUG UNIQUE (TENANT_ID, SLUG)
);

CREATE INDEX IF NOT EXISTS IDX_CHAT_CHANNEL_TENANT ON CHAT_CHANNEL (TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_CHANNEL_TYPE ON CHAT_CHANNEL (TYPE);

CREATE TABLE IF NOT EXISTS CHAT_CHANNEL_MEMBER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CHANNEL_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ROLE VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    LAST_READ_AT TIMESTAMP,
    MUTED SMALLINT DEFAULT 0,
    JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_CHMEM_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES CHAT_CHANNEL (ID),
    CONSTRAINT FK_CHAT_CHMEM_USER FOREIGN KEY (USER_ID) REFERENCES CHAT_USER (ID),
    CONSTRAINT UK_CHAT_CHMEM_CHANNEL_USER UNIQUE (CHANNEL_ID, USER_ID)
);

CREATE INDEX IF NOT EXISTS IDX_CHAT_CHMEM_CHANNEL ON CHAT_CHANNEL_MEMBER (CHANNEL_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_CHMEM_USER ON CHAT_CHANNEL_MEMBER (USER_ID);

CREATE TABLE IF NOT EXISTS CHAT_TENANT_SETTINGS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID VARCHAR(36) NOT NULL,
    MESSAGE_RETENTION_DAYS INT DEFAULT 365,
    MAX_FILE_SIZE_MB INT DEFAULT 50,
    ALLOW_PUBLIC_CHANNELS SMALLINT DEFAULT 1,
    ALLOW_FILE_UPLOADS SMALLINT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_CHAT_TENANT_SETTINGS UNIQUE (TENANT_ID)
);

CREATE TABLE IF NOT EXISTS CHAT_MESSAGE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONVERSATION_ID BIGINT,
    CHANNEL_ID BIGINT,
    SENDER_ID BIGINT NOT NULL,
    TEXT CLOB NOT NULL,
    MESSAGE_TYPE VARCHAR(20) NOT NULL DEFAULT 'TEXT',
    PARENT_MESSAGE_ID BIGINT,
    REPLY_COUNT INT NOT NULL DEFAULT 0,
    LAST_REPLY_AT TIMESTAMP,
    EDITED_AT TIMESTAMP,
    READ_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_MSG_CONVERSATION FOREIGN KEY (CONVERSATION_ID) REFERENCES CHAT_CONVERSATION (ID),
    CONSTRAINT FK_CHAT_MSG_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES CHAT_CHANNEL (ID),
    CONSTRAINT FK_CHAT_MSG_SENDER FOREIGN KEY (SENDER_ID) REFERENCES CHAT_USER (ID),
    CONSTRAINT FK_CHAT_MSG_PARENT FOREIGN KEY (PARENT_MESSAGE_ID) REFERENCES CHAT_MESSAGE (ID)
);

CREATE INDEX IF NOT EXISTS IDX_CHAT_MSG_CONVERSATION ON CHAT_MESSAGE (CONVERSATION_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_MSG_CHANNEL ON CHAT_MESSAGE (CHANNEL_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_MSG_SENDER ON CHAT_MESSAGE (SENDER_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_MSG_CREATED_AT ON CHAT_MESSAGE (CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_CHAT_MSG_PARENT ON CHAT_MESSAGE (PARENT_MESSAGE_ID);

CREATE TABLE IF NOT EXISTS CHAT_REACTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    EMOJI VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_REACTION_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGE (ID),
    CONSTRAINT FK_CHAT_REACTION_USER FOREIGN KEY (USER_ID) REFERENCES CHAT_USER (ID),
    CONSTRAINT UK_CHAT_REACTION_MSG_USER_EMOJI UNIQUE (MESSAGE_ID, USER_ID, EMOJI)
);

CREATE INDEX IF NOT EXISTS IDX_CHAT_REACTION_MESSAGE ON CHAT_REACTION (MESSAGE_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_REACTION_USER ON CHAT_REACTION (USER_ID);

CREATE TABLE IF NOT EXISTS CHAT_MENTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE_ID BIGINT NOT NULL,
    MENTIONED_USER_ID BIGINT,
    MENTION_TYPE VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_MENTION_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGE (ID),
    CONSTRAINT FK_CHAT_MENTION_USER FOREIGN KEY (MENTIONED_USER_ID) REFERENCES CHAT_USER (ID)
);

CREATE INDEX IF NOT EXISTS IDX_CHAT_MENTION_MESSAGE ON CHAT_MENTION (MESSAGE_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_MENTION_USER ON CHAT_MENTION (MENTIONED_USER_ID);

CREATE TABLE IF NOT EXISTS CHAT_ATTACHMENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE_ID BIGINT NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    MIME_TYPE VARCHAR(100) NOT NULL,
    STORAGE_KEY VARCHAR(500) NOT NULL,
    THUMBNAIL_URL VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_ATTACHMENT_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGE (ID)
);

CREATE INDEX IF NOT EXISTS IDX_CHAT_ATTACHMENT_MESSAGE ON CHAT_ATTACHMENT (MESSAGE_ID);

CREATE TABLE IF NOT EXISTS CHAT_NOTIFICATION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID VARCHAR(36) NOT NULL,
    USER_ID BIGINT NOT NULL,
    TYPE VARCHAR(30) NOT NULL,
    CHANNEL_ID BIGINT NULL,
    MESSAGE_ID BIGINT NULL,
    SENDER_ID BIGINT NULL,
    TITLE VARCHAR(255) NOT NULL,
    BODY VARCHAR(500) NULL,
    IS_READ SMALLINT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_NOTIF_USER FOREIGN KEY (USER_ID) REFERENCES CHAT_USER (ID),
    CONSTRAINT FK_CHAT_NOTIF_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES CHAT_CHANNEL (ID),
    CONSTRAINT FK_CHAT_NOTIF_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGE (ID),
    CONSTRAINT FK_CHAT_NOTIF_SENDER FOREIGN KEY (SENDER_ID) REFERENCES CHAT_USER (ID)
);

CREATE INDEX IF NOT EXISTS IDX_CHAT_NOTIF_USER ON CHAT_NOTIFICATION (USER_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_NOTIF_TENANT ON CHAT_NOTIFICATION (TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_CHAT_NOTIF_READ ON CHAT_NOTIFICATION (USER_ID, IS_READ);

CREATE TABLE IF NOT EXISTS CHAT_USER_SETTINGS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    NOTIFY_DM SMALLINT NOT NULL DEFAULT 1,
    NOTIFY_MENTION SMALLINT NOT NULL DEFAULT 1,
    NOTIFY_CHANNEL_MESSAGES SMALLINT NOT NULL DEFAULT 0,
    NOTIFY_SOUND SMALLINT NOT NULL DEFAULT 1,
    NOTIFY_DESKTOP SMALLINT NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_USETTINGS_USER FOREIGN KEY (USER_ID) REFERENCES CHAT_USER (ID),
    CONSTRAINT UK_CHAT_USETTINGS_USER UNIQUE (USER_ID)
);
