--liquibase formatted sql

--changeset lar:001-create-lar-family-members
CREATE TABLE IF NOT EXISTS LAR_FAMILY_MEMBERS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    NICKNAME VARCHAR(50) NULL,
    BIRTH_DATE DATE NULL,
    BLOOD_TYPE VARCHAR(5) NULL,
    ROLE_TYPE VARCHAR(20) NOT NULL,
    SCHOOL_NAME VARCHAR(200) NULL,
    SCHOOL_PHONE VARCHAR(20) NULL,
    SCHOOL_GRADE VARCHAR(50) NULL,
    HEALTH_INSURANCE VARCHAR(100) NULL,
    HEALTH_INSURANCE_NUMBER VARCHAR(50) NULL,
    ALLERGIES JSON NULL,
    MEDICAL_CONDITIONS JSON NULL,
    EMERGENCY_NOTES TEXT NULL,
    AVATAR_URL VARCHAR(500) NULL,
    ACTIVE TINYINT(1) DEFAULT 1,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_FAMILY_MEMBERS_TENANT (TENANT_ID),
    INDEX IDX_LAR_FAMILY_MEMBERS_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-contacts
CREATE TABLE IF NOT EXISTS LAR_CONTACTS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    MEMBER_ID CHAR(36) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    PHONE VARCHAR(20) NULL,
    RELATIONSHIP VARCHAR(30) NOT NULL,
    AGE INT NULL,
    WHERE_MET VARCHAR(200) NULL,
    SCHOOL_NAME VARCHAR(200) NULL,
    PARENT_NAME VARCHAR(200) NULL,
    PARENT_PHONE VARCHAR(20) NULL,
    PARENT_2_NAME VARCHAR(200) NULL,
    PARENT_2_PHONE VARCHAR(20) NULL,
    ADDRESS VARCHAR(500) NULL,
    TRUSTED TINYINT(1) DEFAULT 0,
    NOTES TEXT NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_CONTACTS_TENANT (TENANT_ID),
    INDEX IDX_LAR_CONTACTS_MEMBER (MEMBER_ID),
    CONSTRAINT FK_LAR_CONTACTS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES LAR_FAMILY_MEMBERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-checklist-templates
CREATE TABLE IF NOT EXISTS LAR_CHECKLIST_TEMPLATES (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    ACTIVE TINYINT(1) DEFAULT 1,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_CHECKLIST_TEMPLATES_TENANT (TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-checklist-items
CREATE TABLE IF NOT EXISTS LAR_CHECKLIST_ITEMS (
    ID CHAR(36) NOT NULL,
    TEMPLATE_ID CHAR(36) NOT NULL,
    DESCRIPTION VARCHAR(300) NOT NULL,
    ORDER_INDEX INT DEFAULT 0,
    REQUIRED TINYINT(1) DEFAULT 1,
    REQUIRES_PHOTO TINYINT(1) DEFAULT 0,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_CHECKLIST_ITEMS_TEMPLATE (TEMPLATE_ID),
    CONSTRAINT FK_LAR_CHECKLIST_ITEMS_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES LAR_CHECKLIST_TEMPLATES(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-outing-requests
CREATE TABLE IF NOT EXISTS LAR_OUTING_REQUESTS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    MEMBER_ID CHAR(36) NOT NULL,
    EVENT_NAME VARCHAR(200) NOT NULL,
    EVENT_DATE DATE NOT NULL,
    EVENT_TIME TIME NULL,
    ADDRESS VARCHAR(500) NULL,
    ADDRESS_LAT DECIMAL(10,7) NULL,
    ADDRESS_LNG DECIMAL(10,7) NULL,
    LOCATION_CONTACT_NAME VARCHAR(200) NULL,
    LOCATION_CONTACT_PHONE VARCHAR(20) NULL,
    DEPARTURE_TIME TIME NOT NULL,
    RETURN_METHOD VARCHAR(30) NOT NULL,
    RETURN_METHOD_DETAIL VARCHAR(200) NULL,
    ESTIMATED_RETURN_TIME TIME NOT NULL,
    COMPANIONS JSON NULL,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    APPROVED_BY CHAR(36) NULL,
    APPROVED_AT DATETIME(6) NULL,
    REJECTION_REASON VARCHAR(500) NULL,
    ACTUAL_DEPARTURE DATETIME(6) NULL,
    ACTUAL_RETURN DATETIME(6) NULL,
    PARENT_NOTES TEXT NULL,
    TEEN_NOTES TEXT NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_OUTING_REQUESTS_TENANT (TENANT_ID),
    INDEX IDX_LAR_OUTING_REQUESTS_MEMBER (MEMBER_ID),
    INDEX IDX_LAR_OUTING_REQUESTS_STATUS (TENANT_ID, STATUS),
    CONSTRAINT FK_LAR_OUTING_REQUESTS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES LAR_FAMILY_MEMBERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-checklist-responses
CREATE TABLE IF NOT EXISTS LAR_CHECKLIST_RESPONSES (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    TEMPLATE_ID CHAR(36) NOT NULL,
    OUTING_ID CHAR(36) NULL,
    MEMBER_ID CHAR(36) NOT NULL,
    ALL_PASSED TINYINT(1) DEFAULT 0,
    COMPLETED_AT DATETIME(6) NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_CHECKLIST_RESPONSES_TENANT (TENANT_ID),
    INDEX IDX_LAR_CHECKLIST_RESPONSES_TEMPLATE (TEMPLATE_ID),
    INDEX IDX_LAR_CHECKLIST_RESPONSES_OUTING (OUTING_ID),
    INDEX IDX_LAR_CHECKLIST_RESPONSES_MEMBER (MEMBER_ID),
    CONSTRAINT FK_LAR_CHECKLIST_RESPONSES_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES LAR_CHECKLIST_TEMPLATES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_LAR_CHECKLIST_RESPONSES_OUTING FOREIGN KEY (OUTING_ID) REFERENCES LAR_OUTING_REQUESTS(ID) ON DELETE SET NULL,
    CONSTRAINT FK_LAR_CHECKLIST_RESPONSES_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES LAR_FAMILY_MEMBERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-checklist-response-items
CREATE TABLE IF NOT EXISTS LAR_CHECKLIST_RESPONSE_ITEMS (
    ID CHAR(36) NOT NULL,
    RESPONSE_ID CHAR(36) NOT NULL,
    ITEM_ID CHAR(36) NOT NULL,
    CHECKED TINYINT(1) DEFAULT 0,
    PHOTO_URL VARCHAR(500) NULL,
    NOTE VARCHAR(300) NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_CHECKLIST_RESPONSE_ITEMS_RESPONSE (RESPONSE_ID),
    INDEX IDX_LAR_CHECKLIST_RESPONSE_ITEMS_ITEM (ITEM_ID),
    CONSTRAINT FK_LAR_CHECKLIST_RESPONSE_ITEMS_RESPONSE FOREIGN KEY (RESPONSE_ID) REFERENCES LAR_CHECKLIST_RESPONSES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_LAR_CHECKLIST_RESPONSE_ITEMS_ITEM FOREIGN KEY (ITEM_ID) REFERENCES LAR_CHECKLIST_ITEMS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-health-appointments
CREATE TABLE IF NOT EXISTS LAR_HEALTH_APPOINTMENTS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    MEMBER_ID CHAR(36) NOT NULL,
    DOCTOR_NAME VARCHAR(200) NULL,
    SPECIALTY VARCHAR(100) NULL,
    CLINIC_NAME VARCHAR(200) NULL,
    CLINIC_PHONE VARCHAR(20) NULL,
    CLINIC_ADDRESS VARCHAR(500) NULL,
    APPOINTMENT_DATE DATE NOT NULL,
    APPOINTMENT_TIME TIME NULL,
    STATUS VARCHAR(20) DEFAULT 'SCHEDULED',
    NOTES TEXT NULL,
    PRESCRIPTION_URL VARCHAR(500) NULL,
    FOLLOW_UP_DATE DATE NULL,
    FOLLOW_UP_NOTES VARCHAR(500) NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_HEALTH_APPOINTMENTS_TENANT (TENANT_ID),
    INDEX IDX_LAR_HEALTH_APPOINTMENTS_MEMBER (MEMBER_ID),
    INDEX IDX_LAR_HEALTH_APPOINTMENTS_STATUS (TENANT_ID, STATUS),
    CONSTRAINT FK_LAR_HEALTH_APPOINTMENTS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES LAR_FAMILY_MEMBERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-medications
CREATE TABLE IF NOT EXISTS LAR_MEDICATIONS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    MEMBER_ID CHAR(36) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    DOSAGE VARCHAR(100) NULL,
    FREQUENCY VARCHAR(100) NULL,
    SCHEDULE_TIMES JSON NULL,
    START_DATE DATE NULL,
    END_DATE DATE NULL,
    PRESCRIBING_DOCTOR VARCHAR(200) NULL,
    NOTES TEXT NULL,
    ACTIVE TINYINT(1) DEFAULT 1,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_MEDICATIONS_TENANT (TENANT_ID),
    INDEX IDX_LAR_MEDICATIONS_MEMBER (MEMBER_ID),
    CONSTRAINT FK_LAR_MEDICATIONS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES LAR_FAMILY_MEMBERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-vaccinations
CREATE TABLE IF NOT EXISTS LAR_VACCINATIONS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    MEMBER_ID CHAR(36) NOT NULL,
    VACCINE_NAME VARCHAR(200) NOT NULL,
    DOSE_NUMBER INT NULL,
    DATE_ADMINISTERED DATE NOT NULL,
    LOCATION VARCHAR(200) NULL,
    NEXT_DOSE_DATE DATE NULL,
    CERTIFICATE_URL VARCHAR(500) NULL,
    NOTES VARCHAR(500) NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_VACCINATIONS_TENANT (TENANT_ID),
    INDEX IDX_LAR_VACCINATIONS_MEMBER (MEMBER_ID),
    CONSTRAINT FK_LAR_VACCINATIONS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES LAR_FAMILY_MEMBERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-shopping-lists
CREATE TABLE IF NOT EXISTS LAR_SHOPPING_LISTS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_BY CHAR(36) NOT NULL,
    ASSIGNED_TO CHAR(36) NULL,
    BUDGET_CENTS INT NULL,
    ACTUAL_TOTAL_CENTS INT NULL,
    COMPLETED_AT DATETIME(6) NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_SHOPPING_LISTS_TENANT (TENANT_ID),
    INDEX IDX_LAR_SHOPPING_LISTS_STATUS (TENANT_ID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-shopping-items
CREATE TABLE IF NOT EXISTS LAR_SHOPPING_ITEMS (
    ID CHAR(36) NOT NULL,
    LIST_ID CHAR(36) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    QUANTITY DECIMAL(10,2) NULL,
    UNIT VARCHAR(20) NULL,
    CATEGORY VARCHAR(50) NULL,
    ESTIMATED_PRICE_CENTS INT NULL,
    ACTUAL_PRICE_CENTS INT NULL,
    CHECKED TINYINT(1) DEFAULT 0,
    ADDED_BY CHAR(36) NULL,
    CHECKED_BY CHAR(36) NULL,
    RECURRING TINYINT(1) DEFAULT 0,
    NOTES VARCHAR(200) NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_SHOPPING_ITEMS_LIST (LIST_ID),
    CONSTRAINT FK_LAR_SHOPPING_ITEMS_LIST FOREIGN KEY (LIST_ID) REFERENCES LAR_SHOPPING_LISTS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-pantry-items
CREATE TABLE IF NOT EXISTS LAR_PANTRY_ITEMS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    QUANTITY DECIMAL(10,2) NULL,
    UNIT VARCHAR(20) NULL,
    CATEGORY VARCHAR(50) NULL,
    EXPIRY_DATE DATE NULL,
    STATUS VARCHAR(20) DEFAULT 'OK',
    AUTO_ADD_TO_LIST TINYINT(1) DEFAULT 0,
    PREFERRED_BRAND VARCHAR(100) NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_PANTRY_ITEMS_TENANT (TENANT_ID),
    INDEX IDX_LAR_PANTRY_ITEMS_STATUS (TENANT_ID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-household-bills
CREATE TABLE IF NOT EXISTS LAR_HOUSEHOLD_BILLS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(30) NULL,
    AMOUNT_CENTS INT NOT NULL,
    DUE_DAY INT NULL,
    FREQUENCY VARCHAR(20) DEFAULT 'MONTHLY',
    AUTO_PAY TINYINT(1) DEFAULT 0,
    RESPONSIBLE_MEMBER_ID CHAR(36) NULL,
    NOTES VARCHAR(500) NULL,
    ACTIVE TINYINT(1) DEFAULT 1,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_HOUSEHOLD_BILLS_TENANT (TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-bill-payments
CREATE TABLE IF NOT EXISTS LAR_BILL_PAYMENTS (
    ID CHAR(36) NOT NULL,
    BILL_ID CHAR(36) NOT NULL,
    REFERENCE_MONTH DATE NOT NULL,
    AMOUNT_CENTS INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    PAID_AT DATETIME(6) NULL,
    PAID_BY CHAR(36) NULL,
    RECEIPT_URL VARCHAR(500) NULL,
    NOTES VARCHAR(300) NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_BILL_PAYMENTS_BILL (BILL_ID),
    INDEX IDX_LAR_BILL_PAYMENTS_STATUS (BILL_ID, STATUS),
    CONSTRAINT FK_LAR_BILL_PAYMENTS_BILL FOREIGN KEY (BILL_ID) REFERENCES LAR_HOUSEHOLD_BILLS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-chores
CREATE TABLE IF NOT EXISTS LAR_CHORES (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(500) NULL,
    FREQUENCY VARCHAR(20) NOT NULL,
    DAY_OF_WEEK INT NULL,
    POINTS INT DEFAULT 0,
    ASSIGNMENT_TYPE VARCHAR(20) DEFAULT 'FIXED',
    ASSIGNED_TO CHAR(36) NULL,
    ROTATION_MEMBERS JSON NULL,
    ROTATION_INDEX INT DEFAULT 0,
    ACTIVE TINYINT(1) DEFAULT 1,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_CHORES_TENANT (TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-chore-log
CREATE TABLE IF NOT EXISTS LAR_CHORE_LOG (
    ID CHAR(36) NOT NULL,
    CHORE_ID CHAR(36) NOT NULL,
    MEMBER_ID CHAR(36) NOT NULL,
    COMPLETED_AT DATETIME(6) NOT NULL,
    VERIFIED_BY CHAR(36) NULL,
    VERIFIED_AT DATETIME(6) NULL,
    PHOTO_URL VARCHAR(500) NULL,
    POINTS_EARNED INT DEFAULT 0,
    NOTE VARCHAR(300) NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_CHORE_LOG_CHORE (CHORE_ID),
    INDEX IDX_LAR_CHORE_LOG_MEMBER (MEMBER_ID),
    CONSTRAINT FK_LAR_CHORE_LOG_CHORE FOREIGN KEY (CHORE_ID) REFERENCES LAR_CHORES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_LAR_CHORE_LOG_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES LAR_FAMILY_MEMBERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-rewards
CREATE TABLE IF NOT EXISTS LAR_REWARDS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(500) NULL,
    POINTS_COST INT NOT NULL,
    ACTIVE TINYINT(1) DEFAULT 1,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_REWARDS_TENANT (TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-reward-redemptions
CREATE TABLE IF NOT EXISTS LAR_REWARD_REDEMPTIONS (
    ID CHAR(36) NOT NULL,
    REWARD_ID CHAR(36) NOT NULL,
    MEMBER_ID CHAR(36) NOT NULL,
    POINTS_SPENT INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    APPROVED_BY CHAR(36) NULL,
    REDEEMED_AT DATETIME(6) NULL,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_REWARD_REDEMPTIONS_REWARD (REWARD_ID),
    INDEX IDX_LAR_REWARD_REDEMPTIONS_MEMBER (MEMBER_ID),
    CONSTRAINT FK_LAR_REWARD_REDEMPTIONS_REWARD FOREIGN KEY (REWARD_ID) REFERENCES LAR_REWARDS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_LAR_REWARD_REDEMPTIONS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES LAR_FAMILY_MEMBERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-documents
CREATE TABLE IF NOT EXISTS LAR_DOCUMENTS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    MEMBER_ID CHAR(36) NULL,
    TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(500) NULL,
    CATEGORY VARCHAR(30) NOT NULL,
    FILE_URL VARCHAR(500) NULL,
    EXPIRY_DATE DATE NULL,
    REMINDER_DAYS_BEFORE INT DEFAULT 30,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_DOCUMENTS_TENANT (TENANT_ID),
    INDEX IDX_LAR_DOCUMENTS_MEMBER (MEMBER_ID),
    INDEX IDX_LAR_DOCUMENTS_CATEGORY (TENANT_ID, CATEGORY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset lar:001-create-lar-emergency-cards
CREATE TABLE IF NOT EXISTS LAR_EMERGENCY_CARDS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    MEMBER_ID CHAR(36) NOT NULL,
    BLOOD_TYPE VARCHAR(5) NULL,
    ALLERGIES JSON NULL,
    MEDICAL_CONDITIONS JSON NULL,
    CURRENT_MEDICATIONS JSON NULL,
    EMERGENCY_CONTACT_1 VARCHAR(200) NULL,
    EMERGENCY_PHONE_1 VARCHAR(20) NULL,
    EMERGENCY_CONTACT_2 VARCHAR(200) NULL,
    EMERGENCY_PHONE_2 VARCHAR(20) NULL,
    DOCTOR_NAME VARCHAR(200) NULL,
    DOCTOR_PHONE VARCHAR(20) NULL,
    HEALTH_INSURANCE VARCHAR(200) NULL,
    HEALTH_INSURANCE_NUMBER VARCHAR(50) NULL,
    SPECIAL_INSTRUCTIONS TEXT NULL,
    PUBLIC_TOKEN CHAR(36) NULL,
    ACTIVE TINYINT(1) DEFAULT 1,
    CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_LAR_EMERGENCY_CARDS_TENANT (TENANT_ID),
    INDEX IDX_LAR_EMERGENCY_CARDS_MEMBER (MEMBER_ID),
    UNIQUE INDEX UQ_LAR_EMERGENCY_CARDS_TOKEN (PUBLIC_TOKEN),
    CONSTRAINT FK_LAR_EMERGENCY_CARDS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES LAR_FAMILY_MEMBERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
