-- Schema for notification-service tests
-- =============================================================================
-- EMAIL HISTORY
-- =============================================================================
CREATE TABLE IF NOT EXISTS NOTF_EMAIL_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE_ID VARCHAR(36) NOT NULL UNIQUE,
    USER_ID VARCHAR(36),
    TENANT_ID VARCHAR(36),
    CONFIG_TYPE VARCHAR(20) DEFAULT 'NOTIFICATION',
    CONVERSATION_ID BIGINT,
    RECIPIENT VARCHAR(255) NOT NULL,
    SUBJECT VARCHAR(500),
    TEMPLATE VARCHAR(50) NOT NULL,
    VARIABLES CLOB,
    CONTENT_TEXT TEXT,
    CONTENT_HTML TEXT,
    IN_REPLY_TO VARCHAR(255),
    REFERENCES_HEADER VARCHAR(1000),
    STATUS VARCHAR(20) NOT NULL,
    RETRY_COUNT INT DEFAULT 0 NOT NULL,
    ERROR_MESSAGE TEXT,
    PROVIDER_MESSAGE_ID VARCHAR(255),
    SCHEDULED_AT TIMESTAMP,
    SENT_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_EMAIL_USER_ID ON NOTF_EMAIL_HISTORY(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_EMAIL_TENANT_ID ON NOTF_EMAIL_HISTORY(TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_EMAIL_STATUS ON NOTF_EMAIL_HISTORY(STATUS);
CREATE INDEX IF NOT EXISTS IDX_EMAIL_SCHEDULED ON NOTF_EMAIL_HISTORY(SCHEDULED_AT);
CREATE INDEX IF NOT EXISTS IDX_EMAIL_MESSAGE_ID ON NOTF_EMAIL_HISTORY(MESSAGE_ID);

-- =============================================================================
-- NOTIFICATIONS
-- =============================================================================
CREATE TABLE IF NOT EXISTS NOTF_NOTIFICATIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    MESSAGE TEXT,
    TYPE VARCHAR(50),
    READ_STATUS TINYINT DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- TENANT CONFIG (SMTP/IMAP per tenant)
-- =============================================================================
CREATE TABLE IF NOT EXISTS NOTF_TENANT_CONFIG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID VARCHAR(36) NOT NULL,
    CONFIG_TYPE VARCHAR(20) NOT NULL,
    SMTP_HOST VARCHAR(255),
    SMTP_PORT INT DEFAULT 587,
    SMTP_USERNAME VARCHAR(255),
    SMTP_PASSWORD VARCHAR(255),
    SMTP_USE_TLS TINYINT DEFAULT 1,
    IMAP_HOST VARCHAR(255),
    IMAP_PORT INT DEFAULT 993,
    IMAP_USERNAME VARCHAR(255),
    IMAP_PASSWORD VARCHAR(255),
    IMAP_USE_TLS TINYINT DEFAULT 1,
    IMAP_FOLDER VARCHAR(100) DEFAULT 'INBOX',
    FROM_ADDRESS VARCHAR(255),
    FROM_NAME VARCHAR(255),
    REPLY_TO VARCHAR(255),
    BASE_URL VARCHAR(500) DEFAULT 'http://localhost:3001',
    POLL_INTERVAL_SECONDS INT DEFAULT 30,
    LAST_POLL_AT TIMESTAMP,
    MAX_EMAILS_PER_MINUTE INT DEFAULT 10,
    MAX_EMAILS_PER_HOUR INT DEFAULT 100,
    MAX_EMAILS_PER_DAY INT DEFAULT 500,
    COOLDOWN_SECONDS INT DEFAULT 5,
    ENABLED TINYINT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_TENANT_CONFIG_UNIQUE ON NOTF_TENANT_CONFIG(TENANT_ID, CONFIG_TYPE);

-- =============================================================================
-- RATE LIMIT TRACKER (per tenant per config type)
-- =============================================================================
CREATE TABLE IF NOT EXISTS NOTF_RATE_LIMIT_TRACKER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID VARCHAR(36) NOT NULL,
    CONFIG_TYPE VARCHAR(20) NOT NULL,
    MINUTE_COUNT INT DEFAULT 0,
    MINUTE_WINDOW_START TIMESTAMP,
    HOUR_COUNT INT DEFAULT 0,
    HOUR_WINDOW_START TIMESTAMP,
    DAY_COUNT INT DEFAULT 0,
    DAY_WINDOW_START TIMESTAMP,
    IS_THROTTLED TINYINT DEFAULT 0,
    THROTTLED_UNTIL TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_RATE_LIMIT_UNIQUE ON NOTF_RATE_LIMIT_TRACKER(TENANT_ID, CONFIG_TYPE);

-- =============================================================================
-- MAILS (internal inbox/sent)
-- =============================================================================
CREATE TABLE IF NOT EXISTS NOTF_MAILS (
    ID CHAR(36) PRIMARY KEY,
    USER_ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36),
    SENDER_NAME VARCHAR(255),
    SENDER_EMAIL VARCHAR(255),
    SENDER_IMAGE VARCHAR(500),
    TO_NAME VARCHAR(255),
    TO_EMAIL VARCHAR(255) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    MESSAGE TEXT,
    DATE VARCHAR(100),
    IMPORTANT TINYINT DEFAULT 0 NOT NULL,
    STARRED TINYINT DEFAULT 0 NOT NULL,
    TRASH TINYINT DEFAULT 0 NOT NULL,
    SPAM TINYINT DEFAULT 0 NOT NULL,
    ARCHIVED TINYINT DEFAULT 0 NOT NULL,
    SENT TINYINT DEFAULT 0 NOT NULL,
    READ_STATUS TINYINT DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- CALENDAR EVENTS
-- =============================================================================
CREATE TABLE IF NOT EXISTS NOTF_CALENDAR_EVENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    LOCATION VARCHAR(255),
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME NOT NULL,
    ALL_DAY TINYINT DEFAULT 0 NOT NULL,
    TAG VARCHAR(100),
    BACKGROUND_COLOR VARCHAR(20),
    BORDER_COLOR VARCHAR(20),
    TEXT_COLOR VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- CHAT TABLES (legacy, kept for schema compatibility)
-- =============================================================================
CREATE TABLE IF NOT EXISTS NOTF_CHAT_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EXTERNAL_USER_ID VARCHAR(36) NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    AVATAR_URL VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'OFFLINE' NOT NULL,
    LAST_SEEN_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS NOTF_CHAT_CONVERSATION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID VARCHAR(36) NOT NULL,
    PARTICIPANT_ONE_ID BIGINT NOT NULL,
    PARTICIPANT_TWO_ID BIGINT NOT NULL,
    LAST_MESSAGE_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CONV_PARTICIPANT_ONE FOREIGN KEY (PARTICIPANT_ONE_ID) REFERENCES NOTF_CHAT_USER(ID),
    CONSTRAINT FK_CONV_PARTICIPANT_TWO FOREIGN KEY (PARTICIPANT_TWO_ID) REFERENCES NOTF_CHAT_USER(ID)
);

CREATE TABLE IF NOT EXISTS NOTF_CHAT_MESSAGE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONVERSATION_ID BIGINT NOT NULL,
    SENDER_ID BIGINT NOT NULL,
    TEXT TEXT NOT NULL,
    READ_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MSG_CONVERSATION FOREIGN KEY (CONVERSATION_ID) REFERENCES NOTF_CHAT_CONVERSATION(ID),
    CONSTRAINT FK_MSG_SENDER FOREIGN KEY (SENDER_ID) REFERENCES NOTF_CHAT_USER(ID)
);
