-- Schema para testes H2 (deve espelhar os changesets Liquibase)
-- Kanban Service - Todas as tabelas KANB_

-- ==================== Engine Tables ====================

-- Board Types (Engine configuration)
CREATE TABLE IF NOT EXISTS KANB_BOARD_TYPES (
    CODE VARCHAR(30) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PRODUCT_CODE VARCHAR(50),
    VISIBLE_IN_KANBAN BOOLEAN DEFAULT TRUE,
    SINGLETON BOOLEAN DEFAULT FALSE,
    SCOPE VARCHAR(10) DEFAULT 'TENANT',
    AUTO_CREATE BOOLEAN DEFAULT FALSE,
    NUMBER_PREFIX VARCHAR(10),
    ALLOW_CUSTOM_LISTS BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Board Type Features
CREATE TABLE IF NOT EXISTS KANB_BOARD_TYPE_FEATURES (
    ID CHAR(36) PRIMARY KEY,
    BOARD_TYPE_CODE VARCHAR(30) NOT NULL,
    FEATURE_CODE VARCHAR(30) NOT NULL,
    ENABLED BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (BOARD_TYPE_CODE) REFERENCES KANB_BOARD_TYPES(CODE) ON DELETE CASCADE
);

-- Workflow Steps
CREATE TABLE IF NOT EXISTS KANB_WORKFLOW_STEPS (
    ID CHAR(36) PRIMARY KEY,
    BOARD_TYPE_CODE VARCHAR(30) NOT NULL,
    STEP_CODE VARCHAR(30) NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    POSITION INT DEFAULT 0,
    COLOR VARCHAR(7),
    IS_INITIAL BOOLEAN DEFAULT FALSE,
    IS_FINAL BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOARD_TYPE_CODE) REFERENCES KANB_BOARD_TYPES(CODE) ON DELETE CASCADE
);

-- Workflow Transitions
CREATE TABLE IF NOT EXISTS KANB_WORKFLOW_TRANSITIONS (
    ID CHAR(36) PRIMARY KEY,
    BOARD_TYPE_CODE VARCHAR(30) NOT NULL,
    FROM_STEP_ID CHAR(36) NOT NULL,
    TO_STEP_ID CHAR(36) NOT NULL,
    REQUIRES_COMMENT BOOLEAN DEFAULT FALSE,
    REQUIRES_APPROVAL BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (BOARD_TYPE_CODE) REFERENCES KANB_BOARD_TYPES(CODE) ON DELETE CASCADE,
    FOREIGN KEY (FROM_STEP_ID) REFERENCES KANB_WORKFLOW_STEPS(ID) ON DELETE CASCADE,
    FOREIGN KEY (TO_STEP_ID) REFERENCES KANB_WORKFLOW_STEPS(ID) ON DELETE CASCADE
);

-- Approval Rules
CREATE TABLE IF NOT EXISTS KANB_APPROVAL_RULES (
    ID CHAR(36) PRIMARY KEY,
    TRANSITION_ID CHAR(36) NOT NULL,
    APPROVER_TYPE VARCHAR(20) NOT NULL,
    APPROVER_VALUE VARCHAR(100),
    FALLBACK_USER_ID CHAR(36),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TRANSITION_ID) REFERENCES KANB_WORKFLOW_TRANSITIONS(ID) ON DELETE CASCADE
);

-- Approvals
CREATE TABLE IF NOT EXISTS KANB_APPROVALS (
    ID CHAR(36) PRIMARY KEY,
    TENANT_ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    BOARD_ID CHAR(36) NOT NULL,
    FROM_LIST_ID CHAR(36) NOT NULL,
    TO_LIST_ID CHAR(36) NOT NULL,
    TRANSITION_ID CHAR(36),
    APPROVAL_RULE_ID CHAR(36),
    REQUESTED_BY CHAR(36) NOT NULL,
    REQUESTED_AT TIMESTAMP NOT NULL,
    RESOLVED_BY CHAR(36),
    RESOLVED_AT TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    COMMENT TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_APPROVALS_TENANT_STATUS ON KANB_APPROVALS(TENANT_ID, STATUS);
CREATE INDEX IF NOT EXISTS IDX_APPROVALS_CARD_STATUS ON KANB_APPROVALS(CARD_ID, STATUS);

-- ==================== Core Kanban Tables ====================

-- Boards (Root Aggregate)
CREATE TABLE IF NOT EXISTS KANB_BOARDS (
    ID CHAR(36) PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    BOARD_CODE VARCHAR(50),
    USER_ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    BOARD_TYPE_CODE VARCHAR(30) DEFAULT 'KANBAN',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOARD_TYPE_CODE) REFERENCES KANB_BOARD_TYPES(CODE) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IDX_BOARDS_TENANT ON KANB_BOARDS(TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_BOARDS_USER ON KANB_BOARDS(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_BOARDS_CODE ON KANB_BOARDS(BOARD_CODE);

-- Lists (Child of Board)
CREATE TABLE IF NOT EXISTS KANB_LISTS (
    ID CHAR(36) PRIMARY KEY,
    BOARD_ID CHAR(36) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    POSITION INT NOT NULL,
    WORKFLOW_STEP_ID CHAR(36),
    WIP_LIMIT INT,
    COLOR VARCHAR(7),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOARD_ID) REFERENCES KANB_BOARDS(ID) ON DELETE CASCADE,
    FOREIGN KEY (WORKFLOW_STEP_ID) REFERENCES KANB_WORKFLOW_STEPS(ID) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IDX_LISTS_BOARD ON KANB_LISTS(BOARD_ID);
CREATE INDEX IF NOT EXISTS IDX_LISTS_POSITION ON KANB_LISTS(BOARD_ID, POSITION);

-- Cards (Child of List)
CREATE TABLE IF NOT EXISTS KANB_CARDS (
    ID CHAR(36) PRIMARY KEY,
    LIST_ID CHAR(36) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CARD_NUMBER INT,
    DESCRIPTION TEXT,
    START_DATE DATE,
    DUE_DATE DATE,
    COMPLETED BOOLEAN DEFAULT FALSE,
    PROGRESS INT DEFAULT 0,
    POSITION INT NOT NULL,
    PRIORITY_COLOR VARCHAR(20),
    PRIORITY_TITLE VARCHAR(50),
    ATTACHMENTS INT DEFAULT 0,
    ASSIGNEE_USER_ID CHAR(36),
    SOURCE_SERVICE VARCHAR(30) DEFAULT 'kanban',
    PENDING_APPROVAL BOOLEAN DEFAULT FALSE,
    PENDING_APPROVAL_ID CHAR(36),
    PENDING_TARGET_LIST CHAR(36),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LIST_ID) REFERENCES KANB_LISTS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_CARDS_LIST ON KANB_CARDS(LIST_ID);
CREATE INDEX IF NOT EXISTS IDX_CARDS_POSITION ON KANB_CARDS(LIST_ID, POSITION);
CREATE INDEX IF NOT EXISTS IDX_CARDS_NUMBER ON KANB_CARDS(CARD_NUMBER);
CREATE INDEX IF NOT EXISTS IDX_CARDS_ASSIGNEE ON KANB_CARDS(ASSIGNEE_USER_ID);
CREATE INDEX IF NOT EXISTS IDX_CARDS_DUE_DATE ON KANB_CARDS(DUE_DATE);

-- Labels (Child of Board)
CREATE TABLE IF NOT EXISTS KANB_LABELS (
    ID CHAR(36) PRIMARY KEY,
    BOARD_ID CHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    COLOR VARCHAR(20),
    POSITION INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOARD_ID) REFERENCES KANB_BOARDS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_LABELS_BOARD ON KANB_LABELS(BOARD_ID);

-- Card Labels (Junction table - Child of Card)
CREATE TABLE IF NOT EXISTS KANB_CARD_LABELS (
    ID CHAR(36) PRIMARY KEY,
    CARD_ID CHAR(36) NOT NULL,
    LABEL_ID CHAR(36) NOT NULL,
    POSITION INT NOT NULL,
    FOREIGN KEY (CARD_ID) REFERENCES KANB_CARDS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_CARD_LABELS_CARD ON KANB_CARD_LABELS(CARD_ID);
CREATE INDEX IF NOT EXISTS IDX_CARD_LABELS_LABEL ON KANB_CARD_LABELS(LABEL_ID);

-- Comments (Child of Card)
CREATE TABLE IF NOT EXISTS KANB_COMMENTS (
    ID CHAR(36) PRIMARY KEY,
    CARD_ID CHAR(36) NOT NULL,
    TEXT TEXT NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    POSITION INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CARD_ID) REFERENCES KANB_CARDS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_COMMENTS_CARD ON KANB_COMMENTS(CARD_ID);
CREATE INDEX IF NOT EXISTS IDX_COMMENTS_USER ON KANB_COMMENTS(USER_ID);

-- SubTasks (Child of Card)
CREATE TABLE IF NOT EXISTS KANB_SUBTASKS (
    ID CHAR(36) PRIMARY KEY,
    CARD_ID CHAR(36) NOT NULL,
    TEXT VARCHAR(500) NOT NULL,
    COMPLETED BOOLEAN DEFAULT FALSE,
    POSITION INT NOT NULL,
    ASSIGNEE_USER_ID CHAR(36),
    DUE_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CARD_ID) REFERENCES KANB_CARDS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_SUBTASKS_CARD ON KANB_SUBTASKS(CARD_ID);

-- Attachments (Standalone - references card)
CREATE TABLE IF NOT EXISTS KANB_ATTACHMENTS (
    ID CHAR(36) PRIMARY KEY,
    CARD_ID CHAR(36) NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_SIZE BIGINT,
    CONTENT_TYPE VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_ATTACHMENTS_CARD ON KANB_ATTACHMENTS(CARD_ID);

-- Card History (Audit trail)
CREATE TABLE IF NOT EXISTS KANB_CARD_HISTORY (
    ID CHAR(36) PRIMARY KEY,
    CARD_ID CHAR(36) NOT NULL,
    USER_ID CHAR(36),
    ACTION VARCHAR(50) NOT NULL,
    FIELD_NAME VARCHAR(100),
    OLD_VALUE TEXT,
    NEW_VALUE TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_CARD_HISTORY_CARD ON KANB_CARD_HISTORY(CARD_ID);

-- Card Assignees (Multiple assignees per card)
CREATE TABLE IF NOT EXISTS KANB_CARD_ASSIGNEES (
    ID CHAR(36) PRIMARY KEY,
    CARD_ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CARD_ID) REFERENCES KANB_CARDS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_CARD_ASSIGNEES_CARD ON KANB_CARD_ASSIGNEES(CARD_ID);
CREATE INDEX IF NOT EXISTS IDX_CARD_ASSIGNEES_USER ON KANB_CARD_ASSIGNEES(USER_ID);

-- ArquiGestao Projects: REMOVED (migrated to os-service)
