--liquibase formatted sql

--changeset my-platform:001-create-kanb-users-table
CREATE TABLE KANB_USERS (
    ID CHAR(36) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255),
    FULL_NAME VARCHAR(255),
    NICKNAME VARCHAR(255),
    AVATAR VARCHAR(500),
    ROLE VARCHAR(50) DEFAULT 'USER',
    EMAIL_VERIFIED TINYINT(1) DEFAULT 0,
    ENABLED TINYINT(1) DEFAULT 1,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset my-platform:001-create-kanb-boards-table
CREATE TABLE KANB_BOARDS (
    ID CHAR(36) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    USER_ID CHAR(36),
    BOARD_CODE VARCHAR(10),
    TENANT_ID CHAR(36),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_BOARDS ADD CONSTRAINT FK_KANB_BOARDS_USER FOREIGN KEY (USER_ID) REFERENCES KANB_USERS(ID) ON DELETE SET NULL;
CREATE INDEX IDX_KANB_BOARDS_TENANT ON KANB_BOARDS (TENANT_ID);

--changeset my-platform:001-create-kanb-lists-table
CREATE TABLE KANB_LISTS (
    ID CHAR(36) NOT NULL,
    BOARD_ID CHAR(36) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    POSITION INT DEFAULT 0,
    TENANT_ID CHAR(36),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_LISTS ADD CONSTRAINT FK_KANB_LISTS_BOARD FOREIGN KEY (BOARD_ID) REFERENCES KANB_BOARDS(ID) ON DELETE CASCADE;
CREATE INDEX IDX_KANB_LISTS_TENANT ON KANB_LISTS (TENANT_ID);

--changeset my-platform:001-create-kanb-cards-table
CREATE TABLE KANB_CARDS (
    ID CHAR(36) NOT NULL,
    LIST_ID CHAR(36) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    START_DATE DATE,
    DUE_DATE DATE,
    COMPLETED TINYINT(1) DEFAULT 0,
    PROGRESS INT DEFAULT 0,
    POSITION INT DEFAULT 0,
    PRIORITY_COLOR VARCHAR(50),
    PRIORITY_TITLE VARCHAR(100),
    ATTACHMENTS INT DEFAULT 0,
    ASSIGNEE_USER_ID CHAR(36),
    CARD_NUMBER INT,
    TENANT_ID CHAR(36),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_CARDS ADD CONSTRAINT FK_KANB_CARDS_LIST FOREIGN KEY (LIST_ID) REFERENCES KANB_LISTS(ID) ON DELETE CASCADE;
CREATE INDEX IDX_KANB_CARDS_TENANT ON KANB_CARDS (TENANT_ID);

--changeset my-platform:001-create-kanb-card-assignees-table
CREATE TABLE KANB_CARD_ASSIGNEES (
    CARD_ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    PRIMARY KEY (CARD_ID, USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_CARD_ASSIGNEES ADD CONSTRAINT FK_KANB_ASSIGNEES_CARD FOREIGN KEY (CARD_ID) REFERENCES KANB_CARDS(ID) ON DELETE CASCADE;
ALTER TABLE KANB_CARD_ASSIGNEES ADD CONSTRAINT FK_KANB_ASSIGNEES_USER FOREIGN KEY (USER_ID) REFERENCES KANB_USERS(ID) ON DELETE CASCADE;

--changeset my-platform:001-create-kanb-comments-table
CREATE TABLE KANB_COMMENTS (
    ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    USER_ID CHAR(36),
    TEXT TEXT NOT NULL,
    POSITION INT DEFAULT 0,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_COMMENTS ADD CONSTRAINT FK_KANB_COMMENTS_CARD FOREIGN KEY (CARD_ID) REFERENCES KANB_CARDS(ID) ON DELETE CASCADE;
ALTER TABLE KANB_COMMENTS ADD CONSTRAINT FK_KANB_COMMENTS_USER FOREIGN KEY (USER_ID) REFERENCES KANB_USERS(ID) ON DELETE SET NULL;

--changeset my-platform:001-create-kanb-subtasks-table
CREATE TABLE KANB_SUBTASKS (
    ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    TEXT VARCHAR(500) NOT NULL,
    COMPLETED TINYINT(1) DEFAULT 0,
    POSITION INT DEFAULT 0,
    ASSIGNEE_USER_ID CHAR(36),
    DUE_DATE DATE,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_SUBTASKS ADD CONSTRAINT FK_KANB_SUBTASKS_CARD FOREIGN KEY (CARD_ID) REFERENCES KANB_CARDS(ID) ON DELETE CASCADE;

--changeset my-platform:001-create-kanb-attachments-table
CREATE TABLE KANB_ATTACHMENTS (
    ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_SIZE BIGINT,
    CONTENT_TYPE VARCHAR(100),
    TENANT_ID CHAR(36),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_ATTACHMENTS ADD CONSTRAINT FK_KANB_ATTACHMENTS_CARD FOREIGN KEY (CARD_ID) REFERENCES KANB_CARDS(ID) ON DELETE CASCADE;
CREATE INDEX IDX_KANB_ATTACHMENTS_TENANT ON KANB_ATTACHMENTS (TENANT_ID);
CREATE INDEX IDX_KANB_ATTACHMENTS_CARD ON KANB_ATTACHMENTS (CARD_ID);

--changeset my-platform:001-create-kanb-labels-table
CREATE TABLE KANB_LABELS (
    ID CHAR(36) NOT NULL,
    BOARD_ID CHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    COLOR VARCHAR(50) NOT NULL,
    POSITION INT DEFAULT 0,
    TENANT_ID CHAR(36),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_LABELS ADD CONSTRAINT FK_KANB_LABELS_BOARD FOREIGN KEY (BOARD_ID) REFERENCES KANB_BOARDS(ID) ON DELETE CASCADE;
CREATE INDEX IDX_KANB_LABELS_BOARD ON KANB_LABELS (BOARD_ID);
CREATE INDEX IDX_KANB_LABELS_TENANT ON KANB_LABELS (TENANT_ID);

--changeset my-platform:001-create-kanb-card-labels-table
CREATE TABLE KANB_CARD_LABELS (
    ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    LABEL_ID CHAR(36) NOT NULL,
    POSITION INT DEFAULT 0,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_CARD_LABELS ADD CONSTRAINT FK_KANB_CARDLABELS_CARD FOREIGN KEY (CARD_ID) REFERENCES KANB_CARDS(ID) ON DELETE CASCADE;
ALTER TABLE KANB_CARD_LABELS ADD CONSTRAINT FK_KANB_CARDLABELS_LABEL FOREIGN KEY (LABEL_ID) REFERENCES KANB_LABELS(ID) ON DELETE CASCADE;
CREATE INDEX IDX_KANB_CARD_LABELS_CARD ON KANB_CARD_LABELS (CARD_ID);
CREATE INDEX IDX_KANB_CARD_LABELS_LABEL ON KANB_CARD_LABELS (LABEL_ID);
CREATE UNIQUE INDEX UK_KANB_CARD_LABEL ON KANB_CARD_LABELS (CARD_ID, LABEL_ID);

--changeset my-platform:001-create-kanb-tasks-table
CREATE TABLE KANB_TASKS (
    ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36),
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    STATUS INT NOT NULL DEFAULT 0,
    COMPLETED TINYINT(1) NOT NULL DEFAULT 0,
    START_DATE DATE,
    END_DATE DATE,
    POSITION INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_TASKS ADD CONSTRAINT FK_KANB_TASKS_USER FOREIGN KEY (USER_ID) REFERENCES KANB_USERS(ID) ON DELETE CASCADE;
CREATE INDEX IDX_KANB_TASKS_USER ON KANB_TASKS (USER_ID);
CREATE INDEX IDX_KANB_TASKS_TENANT ON KANB_TASKS (TENANT_ID);
CREATE INDEX IDX_KANB_TASKS_STATUS ON KANB_TASKS (STATUS);

--changeset my-platform:001-create-kanb-task-assignees-table
CREATE TABLE KANB_TASK_ASSIGNEES (
    ID CHAR(36) NOT NULL,
    TASK_ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    POSITION INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_TASK_ASSIGNEES ADD CONSTRAINT FK_KANB_TASKASSIGNEES_TASK FOREIGN KEY (TASK_ID) REFERENCES KANB_TASKS(ID) ON DELETE CASCADE;
ALTER TABLE KANB_TASK_ASSIGNEES ADD CONSTRAINT FK_KANB_TASKASSIGNEES_USER FOREIGN KEY (USER_ID) REFERENCES KANB_USERS(ID) ON DELETE CASCADE;
CREATE INDEX IDX_KANB_TASK_ASSIGNEES_TASK ON KANB_TASK_ASSIGNEES (TASK_ID);
CREATE INDEX IDX_KANB_TASK_ASSIGNEES_USER ON KANB_TASK_ASSIGNEES (USER_ID);
CREATE UNIQUE INDEX UK_KANB_TASK_ASSIGNEE ON KANB_TASK_ASSIGNEES (TASK_ID, USER_ID);

--changeset my-platform:001-create-kanb-card-history-table
CREATE TABLE KANB_CARD_HISTORY (
    ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    BOARD_ID CHAR(36),
    CHANGED_BY CHAR(36) NOT NULL,
    CHANGED_BY_NAME VARCHAR(255),
    CHANGE_TYPE VARCHAR(50) NOT NULL,
    CHANGES_JSON TEXT,
    COMMENT TEXT,
    SNAPSHOT_JSON TEXT,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX IDX_KANB_CARD_HISTORY_CARD ON KANB_CARD_HISTORY (CARD_ID);
CREATE INDEX IDX_KANB_CARD_HISTORY_BOARD ON KANB_CARD_HISTORY (BOARD_ID);
CREATE INDEX IDX_KANB_CARD_HISTORY_CREATED ON KANB_CARD_HISTORY (CREATED_AT);

