--liquibase formatted sql

--changeset my-platform:002-add-gtd-columns-to-tasks
ALTER TABLE KANB_TASKS ADD COLUMN GTD_TYPE VARCHAR(20) NULL;
ALTER TABLE KANB_TASKS ADD COLUMN GTD_CONTEXT_ID CHAR(36) NULL;
ALTER TABLE KANB_TASKS ADD COLUMN GTD_PROJECT_ID CHAR(36) NULL;
ALTER TABLE KANB_TASKS ADD COLUMN GTD_ENERGY VARCHAR(10) NULL;
ALTER TABLE KANB_TASKS ADD COLUMN GTD_TIME_ESTIMATE INT NULL;
ALTER TABLE KANB_TASKS ADD COLUMN GTD_PRIORITY INT NULL;
ALTER TABLE KANB_TASKS ADD COLUMN GTD_DELEGATED_TO VARCHAR(255) NULL;
ALTER TABLE KANB_TASKS ADD COLUMN GTD_WAITING_SINCE DATE NULL;
ALTER TABLE KANB_TASKS ADD COLUMN GTD_REVIEW_DATE DATE NULL;
ALTER TABLE KANB_TASKS ADD COLUMN GTD_NOTES TEXT NULL;
CREATE INDEX IDX_KANB_TASKS_GTD_TYPE ON KANB_TASKS (GTD_TYPE);
CREATE INDEX IDX_KANB_TASKS_GTD_CTX ON KANB_TASKS (GTD_CONTEXT_ID);
CREATE INDEX IDX_KANB_TASKS_GTD_PROJ ON KANB_TASKS (GTD_PROJECT_ID);
CREATE INDEX IDX_KANB_TASKS_GTD_COMPOSITE ON KANB_TASKS (USER_ID, TENANT_ID, GTD_TYPE);

--changeset my-platform:002-create-kanb-gtd-contexts
CREATE TABLE KANB_GTD_CONTEXTS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ICON VARCHAR(50) NULL,
    COLOR VARCHAR(20) NULL,
    POSITION INT NOT NULL DEFAULT 0,
    IS_DEFAULT TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX IDX_GTD_CTX_USER_TENANT ON KANB_GTD_CONTEXTS (USER_ID, TENANT_ID);
CREATE UNIQUE INDEX UK_GTD_CTX_NAME ON KANB_GTD_CONTEXTS (TENANT_ID, USER_ID, NAME);

--changeset my-platform:002-create-kanb-gtd-projects
CREATE TABLE KANB_GTD_PROJECTS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NULL,
    OUTCOME VARCHAR(500) NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'active',
    POSITION INT NOT NULL DEFAULT 0,
    DUE_DATE DATE NULL,
    REVIEW_DATE DATE NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX IDX_GTD_PROJ_USER_TENANT ON KANB_GTD_PROJECTS (USER_ID, TENANT_ID);
CREATE INDEX IDX_GTD_PROJ_STATUS ON KANB_GTD_PROJECTS (STATUS);

--changeset my-platform:002-create-kanb-gtd-review-log
CREATE TABLE KANB_GTD_REVIEW_LOG (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    REVIEW_TYPE VARCHAR(20) NOT NULL DEFAULT 'weekly',
    STARTED_AT TIMESTAMP(6) NOT NULL,
    COMPLETED_AT TIMESTAMP(6) NULL,
    ITEMS_REVIEWED INT NOT NULL DEFAULT 0,
    ITEMS_PROCESSED INT NOT NULL DEFAULT 0,
    ITEMS_COMPLETED INT NOT NULL DEFAULT 0,
    ITEMS_CREATED INT NOT NULL DEFAULT 0,
    NOTES TEXT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX IDX_GTD_REVIEW_USER ON KANB_GTD_REVIEW_LOG (USER_ID, TENANT_ID);

--changeset my-platform:002-add-gtd-foreign-keys
ALTER TABLE KANB_TASKS ADD CONSTRAINT FK_KANB_TASKS_GTD_CTX
    FOREIGN KEY (GTD_CONTEXT_ID) REFERENCES KANB_GTD_CONTEXTS(ID) ON DELETE SET NULL;
ALTER TABLE KANB_TASKS ADD CONSTRAINT FK_KANB_TASKS_GTD_PROJ
    FOREIGN KEY (GTD_PROJECT_ID) REFERENCES KANB_GTD_PROJECTS(ID) ON DELETE SET NULL;
