--liquibase formatted sql

--changeset my-platform:003-create-kanb-arq-projects
CREATE TABLE KANB_ARQ_PROJECTS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CLIENT_NAME VARCHAR(255) NULL,
    PHASE VARCHAR(20) NOT NULL DEFAULT 'BRIEFING',
    START_DATE DATE NULL,
    EXPECTED_END_DATE DATE NULL,
    BUDGET DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    SPENT DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    PROGRESS INT NOT NULL DEFAULT 0,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX IDX_KANB_ARQ_PROJ_TENANT ON KANB_ARQ_PROJECTS (TENANT_ID);
CREATE INDEX IDX_KANB_ARQ_PROJ_STATUS ON KANB_ARQ_PROJECTS (STATUS);
CREATE INDEX IDX_KANB_ARQ_PROJ_PHASE ON KANB_ARQ_PROJECTS (PHASE);
CREATE INDEX IDX_KANB_ARQ_PROJ_TENANT_STATUS ON KANB_ARQ_PROJECTS (TENANT_ID, STATUS);
