--liquibase formatted sql

--changeset my-platform:004-drop-kanb-arq-projects
--comment: ArquiGestao migrated to os-service. Drop table from kanban.
DROP INDEX IDX_KANB_ARQ_PROJ_TENANT_STATUS ON KANB_ARQ_PROJECTS;
DROP INDEX IDX_KANB_ARQ_PROJ_PHASE ON KANB_ARQ_PROJECTS;
DROP INDEX IDX_KANB_ARQ_PROJ_STATUS ON KANB_ARQ_PROJECTS;
DROP INDEX IDX_KANB_ARQ_PROJ_TENANT ON KANB_ARQ_PROJECTS;
DROP TABLE KANB_ARQ_PROJECTS;
