--liquibase formatted sql

--changeset my-platform:005-create-kanb-board-types
--comment: Board type configuration per product (engine, workflow, features)
CREATE TABLE KANB_BOARD_TYPES (
    CODE VARCHAR(30) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PRODUCT_CODE VARCHAR(50),
    VISIBLE_IN_KANBAN TINYINT(1) DEFAULT 1,
    SINGLETON TINYINT(1) DEFAULT 0,
    SCOPE VARCHAR(10) DEFAULT 'TENANT',
    AUTO_CREATE TINYINT(1) DEFAULT 0,
    NUMBER_PREFIX VARCHAR(10),
    ALLOW_CUSTOM_LISTS TINYINT(1) DEFAULT 1,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset my-platform:005-create-kanb-board-type-features
--comment: Features enabled per board type (comments, subtasks, labels, etc)
CREATE TABLE KANB_BOARD_TYPE_FEATURES (
    ID CHAR(36) NOT NULL,
    BOARD_TYPE_CODE VARCHAR(30) NOT NULL,
    FEATURE_CODE VARCHAR(30) NOT NULL,
    ENABLED TINYINT(1) DEFAULT 1,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_BOARD_TYPE_FEATURES ADD CONSTRAINT FK_KANB_BTF_BOARD_TYPE FOREIGN KEY (BOARD_TYPE_CODE) REFERENCES KANB_BOARD_TYPES(CODE) ON DELETE CASCADE;
CREATE UNIQUE INDEX UK_KANB_BTF_TYPE_FEATURE ON KANB_BOARD_TYPE_FEATURES (BOARD_TYPE_CODE, FEATURE_CODE);

--changeset my-platform:005-create-kanb-workflow-steps
--comment: Pre-defined workflow steps (lists) per board type
CREATE TABLE KANB_WORKFLOW_STEPS (
    ID CHAR(36) NOT NULL,
    BOARD_TYPE_CODE VARCHAR(30) NOT NULL,
    STEP_CODE VARCHAR(30) NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    POSITION INT DEFAULT 0,
    COLOR VARCHAR(7),
    IS_INITIAL TINYINT(1) DEFAULT 0,
    IS_FINAL TINYINT(1) DEFAULT 0,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_WORKFLOW_STEPS ADD CONSTRAINT FK_KANB_WFS_BOARD_TYPE FOREIGN KEY (BOARD_TYPE_CODE) REFERENCES KANB_BOARD_TYPES(CODE) ON DELETE CASCADE;
CREATE UNIQUE INDEX UK_KANB_WFS_TYPE_CODE ON KANB_WORKFLOW_STEPS (BOARD_TYPE_CODE, STEP_CODE);

--changeset my-platform:005-create-kanb-workflow-transitions
--comment: Allowed transitions between workflow steps
CREATE TABLE KANB_WORKFLOW_TRANSITIONS (
    ID CHAR(36) NOT NULL,
    BOARD_TYPE_CODE VARCHAR(30) NOT NULL,
    FROM_STEP_ID CHAR(36) NOT NULL,
    TO_STEP_ID CHAR(36) NOT NULL,
    REQUIRES_COMMENT TINYINT(1) DEFAULT 0,
    REQUIRES_APPROVAL TINYINT(1) DEFAULT 0,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_WORKFLOW_TRANSITIONS ADD CONSTRAINT FK_KANB_WFT_BOARD_TYPE FOREIGN KEY (BOARD_TYPE_CODE) REFERENCES KANB_BOARD_TYPES(CODE) ON DELETE CASCADE;
ALTER TABLE KANB_WORKFLOW_TRANSITIONS ADD CONSTRAINT FK_KANB_WFT_FROM_STEP FOREIGN KEY (FROM_STEP_ID) REFERENCES KANB_WORKFLOW_STEPS(ID) ON DELETE CASCADE;
ALTER TABLE KANB_WORKFLOW_TRANSITIONS ADD CONSTRAINT FK_KANB_WFT_TO_STEP FOREIGN KEY (TO_STEP_ID) REFERENCES KANB_WORKFLOW_STEPS(ID) ON DELETE CASCADE;
CREATE UNIQUE INDEX UK_KANB_WFT_FROM_TO ON KANB_WORKFLOW_TRANSITIONS (BOARD_TYPE_CODE, FROM_STEP_ID, TO_STEP_ID);

--changeset my-platform:005-create-kanb-approval-rules
--comment: Who approves each transition (specific user, board owner, etc)
CREATE TABLE KANB_APPROVAL_RULES (
    ID CHAR(36) NOT NULL,
    TRANSITION_ID CHAR(36) NOT NULL,
    APPROVER_TYPE VARCHAR(20) NOT NULL,
    APPROVER_VALUE VARCHAR(100),
    FALLBACK_USER_ID CHAR(36),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_APPROVAL_RULES ADD CONSTRAINT FK_KANB_APR_TRANSITION FOREIGN KEY (TRANSITION_ID) REFERENCES KANB_WORKFLOW_TRANSITIONS(ID) ON DELETE CASCADE;

--changeset my-platform:005-create-kanb-approvals
--comment: Approval requests and history for workflow transitions
CREATE TABLE KANB_APPROVALS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    BOARD_ID CHAR(36) NOT NULL,
    FROM_LIST_ID CHAR(36) NOT NULL,
    TO_LIST_ID CHAR(36) NOT NULL,
    TRANSITION_ID CHAR(36),
    APPROVAL_RULE_ID CHAR(36),
    REQUESTED_BY CHAR(36) NOT NULL,
    REQUESTED_AT TIMESTAMP(6) NOT NULL,
    RESOLVED_BY CHAR(36),
    RESOLVED_AT TIMESTAMP(6),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    COMMENT TEXT,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_APPROVALS ADD CONSTRAINT FK_KANB_APV_TRANSITION FOREIGN KEY (TRANSITION_ID) REFERENCES KANB_WORKFLOW_TRANSITIONS(ID) ON DELETE SET NULL;
ALTER TABLE KANB_APPROVALS ADD CONSTRAINT FK_KANB_APV_RULE FOREIGN KEY (APPROVAL_RULE_ID) REFERENCES KANB_APPROVAL_RULES(ID) ON DELETE SET NULL;
CREATE INDEX IDX_KANB_APPROVALS_TENANT_STATUS ON KANB_APPROVALS (TENANT_ID, STATUS);
CREATE INDEX IDX_KANB_APPROVALS_CARD_STATUS ON KANB_APPROVALS (CARD_ID, STATUS);
CREATE INDEX IDX_KANB_APPROVALS_REQUESTED_BY ON KANB_APPROVALS (REQUESTED_BY);

--changeset my-platform:005-alter-kanb-boards-add-engine-columns
--comment: Add board type and active flag to boards
ALTER TABLE KANB_BOARDS ADD COLUMN BOARD_TYPE_CODE VARCHAR(30) DEFAULT 'KANBAN';
ALTER TABLE KANB_BOARDS ADD COLUMN IS_ACTIVE TINYINT(1) DEFAULT 1;
ALTER TABLE KANB_BOARDS ADD CONSTRAINT FK_KANB_BOARDS_TYPE FOREIGN KEY (BOARD_TYPE_CODE) REFERENCES KANB_BOARD_TYPES(CODE) ON DELETE SET NULL;

--changeset my-platform:005-alter-kanb-lists-add-workflow-columns
--comment: Link lists to workflow steps, add WIP limit and color
ALTER TABLE KANB_LISTS ADD COLUMN WORKFLOW_STEP_ID CHAR(36);
ALTER TABLE KANB_LISTS ADD COLUMN WIP_LIMIT INT;
ALTER TABLE KANB_LISTS ADD COLUMN COLOR VARCHAR(7);
ALTER TABLE KANB_LISTS ADD CONSTRAINT FK_KANB_LISTS_WF_STEP FOREIGN KEY (WORKFLOW_STEP_ID) REFERENCES KANB_WORKFLOW_STEPS(ID) ON DELETE SET NULL;

--changeset my-platform:005-alter-kanb-cards-add-engine-columns
--comment: Add source service and approval tracking to cards
ALTER TABLE KANB_CARDS ADD COLUMN SOURCE_SERVICE VARCHAR(30) DEFAULT 'kanban';
ALTER TABLE KANB_CARDS ADD COLUMN PENDING_APPROVAL TINYINT(1) DEFAULT 0;
ALTER TABLE KANB_CARDS ADD COLUMN PENDING_APPROVAL_ID CHAR(36);
ALTER TABLE KANB_CARDS ADD COLUMN PENDING_TARGET_LIST CHAR(36);

--changeset my-platform:005-drop-gtd-task-tables
--comment: GTD and Tasks migrated to gtd-service. Drop FKs first, then tables.
ALTER TABLE KANB_TASKS DROP FOREIGN KEY FK_KANB_TASKS_GTD_CTX;
ALTER TABLE KANB_TASKS DROP FOREIGN KEY FK_KANB_TASKS_GTD_PROJ;
ALTER TABLE KANB_TASKS DROP FOREIGN KEY FK_KANB_TASKS_USER;
ALTER TABLE KANB_TASK_ASSIGNEES DROP FOREIGN KEY FK_KANB_TASKASSIGNEES_TASK;
ALTER TABLE KANB_TASK_ASSIGNEES DROP FOREIGN KEY FK_KANB_TASKASSIGNEES_USER;
DROP TABLE KANB_GTD_REVIEW_LOG;
DROP TABLE KANB_GTD_PROJECTS;
DROP TABLE KANB_GTD_CONTEXTS;
DROP TABLE KANB_TASK_ASSIGNEES;
DROP TABLE KANB_TASKS;

--changeset my-platform:005-drop-kanb-users
--comment: KANB_USERS no longer needed. Drop FKs referencing it, then drop table.
ALTER TABLE KANB_CARD_ASSIGNEES DROP FOREIGN KEY FK_KANB_ASSIGNEES_USER;
ALTER TABLE KANB_COMMENTS DROP FOREIGN KEY FK_KANB_COMMENTS_USER;
ALTER TABLE KANB_BOARDS DROP FOREIGN KEY FK_KANB_BOARDS_USER;
DROP TABLE KANB_USERS;
