--liquibase formatted sql

--changeset my-platform:006-create-kanb-acceptance-criteria-table
CREATE TABLE KANB_ACCEPTANCE_CRITERIA (
    ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    TEXT VARCHAR(500) NOT NULL,
    COMPLETED TINYINT(1) DEFAULT 0,
    POSITION INT DEFAULT 0,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE KANB_ACCEPTANCE_CRITERIA ADD CONSTRAINT FK_KANB_ACC_CRITERIA_CARD FOREIGN KEY (CARD_ID) REFERENCES KANB_CARDS(ID) ON DELETE CASCADE;
