--liquibase formatted sql

-- ============================================================================
-- AUTH_USERS - Tabela principal de usuarios
-- ============================================================================

--changeset my-platform:structure-001-create-auth-users
CREATE TABLE AUTH_USERS (
    ID CHAR(36) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255),
    FULL_NAME VARCHAR(255),
    NICKNAME VARCHAR(255),
    AVATAR VARCHAR(500),
    EMAIL_VERIFIED TINYINT(1) DEFAULT 0,
    ENABLED TINYINT(1) DEFAULT 1,
    FAILED_LOGIN_ATTEMPTS INT NOT NULL DEFAULT 0,
    LOCKED_UNTIL TIMESTAMP(6),
    TWO_FACTOR_ENABLED TINYINT(1) NOT NULL DEFAULT 0,
    TWO_FACTOR_METHOD VARCHAR(20) DEFAULT 'EMAIL',
    TOTP_SECRET VARCHAR(64),
    TOTP_VERIFIED_AT TIMESTAMP(6),
    DELETED_AT TIMESTAMP(6),
    DELETED_BY CHAR(36),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX IDX_AUTH_USERS_EMAIL ON AUTH_USERS (EMAIL);
