--liquibase formatted sql

-- ============================================================================
-- AUTH_USER_SESSIONS - Sessoes ativas do usuario
-- ============================================================================

--changeset my-platform:structure-005-create-auth-user-sessions
CREATE TABLE AUTH_USER_SESSIONS (
    ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    TOKEN_ID CHAR(36) NOT NULL,
    DEVICE_NAME VARCHAR(255),
    DEVICE_TYPE VARCHAR(50),
    BROWSER VARCHAR(100),
    OPERATING_SYSTEM VARCHAR(100),
    IP_ADDRESS VARCHAR(45),
    LOCATION VARCHAR(255),
    IS_CURRENT TINYINT(1) DEFAULT 0,
    LAST_ACTIVITY_AT TIMESTAMP(6),
    EXPIRES_AT TIMESTAMP(6) NOT NULL,
    REVOKED TINYINT(1) DEFAULT 0,
    REVOKED_AT TIMESTAMP(6),
    REVOKED_REASON VARCHAR(255),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE AUTH_USER_SESSIONS ADD CONSTRAINT FK_USER_SESSIONS_USER FOREIGN KEY (USER_ID) REFERENCES AUTH_USERS(ID) ON DELETE CASCADE;
CREATE INDEX IDX_USER_SESSIONS_USER ON AUTH_USER_SESSIONS (USER_ID);
CREATE UNIQUE INDEX IDX_USER_SESSIONS_TOKEN ON AUTH_USER_SESSIONS (TOKEN_ID);
CREATE INDEX IDX_USER_SESSIONS_EXPIRES ON AUTH_USER_SESSIONS (EXPIRES_AT);
