--liquibase formatted sql

-- ============================================================================
-- AUTH_AUDIT_LOG - Log de auditoria de acoes de autenticacao
-- ============================================================================

--changeset my-platform:structure-006-create-auth-audit-log
CREATE TABLE AUTH_AUDIT_LOG (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36),
    USER_ID CHAR(36),
    EMAIL VARCHAR(255),
    ACTION VARCHAR(100) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    RESOURCE_TYPE VARCHAR(50),
    RESOURCE_ID CHAR(36),
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    FAILURE_REASON VARCHAR(255),
    METADATA TEXT,
    CREATED_AT TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX IDX_AUDIT_LOG_USER_ID ON AUTH_AUDIT_LOG (USER_ID);
CREATE INDEX IDX_AUDIT_LOG_EMAIL ON AUTH_AUDIT_LOG (EMAIL);
CREATE INDEX IDX_AUDIT_LOG_ACTION ON AUTH_AUDIT_LOG (ACTION);
CREATE INDEX IDX_AUDIT_LOG_CREATED_AT ON AUTH_AUDIT_LOG (CREATED_AT);
CREATE INDEX IDX_AUTH_AUDIT_LOG_TENANT_ID ON AUTH_AUDIT_LOG (TENANT_ID);
CREATE INDEX IDX_AUTH_AUDIT_LOG_TENANT_DATE ON AUTH_AUDIT_LOG (TENANT_ID, CREATED_AT);
CREATE INDEX IDX_AUTH_AUDIT_LOG_RESOURCE ON AUTH_AUDIT_LOG (RESOURCE_TYPE, RESOURCE_ID);
CREATE INDEX IDX_AUTH_AUDIT_LOG_STATUS ON AUTH_AUDIT_LOG (STATUS, CREATED_AT);
