spring:
  application:
    name: chat-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
    tags:
      application: ${spring.application.name}
      environment: ${ENVIRONMENT:development}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://127.0.0.1:4318/v1/traces
      timeout: 10s
      compression: gzip

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    com.poc: DEBUG

loki:
  enabled: true
  url: http://127.0.0.1:3100/loki/api/v1/push
