--liquibase formatted sql

--changeset chat:001-1-create-chat-user-table
CREATE TABLE IF NOT EXISTS CHAT_USER (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    EXTERNAL_USER_ID VARCHAR(36) NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    AVATAR_URL VARCHAR(500) NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'OFFLINE',
    LAST_SEEN_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_CHAT_USER_EXTERNAL_ID ON CHAT_USER (EXTERNAL_USER_ID);
CREATE INDEX IDX_CHAT_USER_TENANT ON CHAT_USER (TENANT_ID);

--changeset chat:001-2-chat-user-unique-constraint
ALTER TABLE CHAT_USER ADD CONSTRAINT UK_CHAT_USER_EXT_TENANT UNIQUE (EXTERNAL_USER_ID, TENANT_ID);
--rollback ALTER TABLE CHAT_USER DROP INDEX UK_CHAT_USER_EXT_TENANT;

--changeset chat:001-3-create-chat-conversation-table
CREATE TABLE IF NOT EXISTS CHAT_CONVERSATION (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    PARTICIPANT_ONE_ID BIGINT NOT NULL,
    PARTICIPANT_TWO_ID BIGINT NOT NULL,
    LAST_MESSAGE_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CHAT_CONV_PARTICIPANT_ONE FOREIGN KEY (PARTICIPANT_ONE_ID) REFERENCES CHAT_USER (ID),
    CONSTRAINT FK_CHAT_CONV_PARTICIPANT_TWO FOREIGN KEY (PARTICIPANT_TWO_ID) REFERENCES CHAT_USER (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_CHAT_CONV_TENANT ON CHAT_CONVERSATION (TENANT_ID);
CREATE INDEX IDX_CHAT_CONV_PARTICIPANT_ONE ON CHAT_CONVERSATION (PARTICIPANT_ONE_ID);
CREATE INDEX IDX_CHAT_CONV_PARTICIPANT_TWO ON CHAT_CONVERSATION (PARTICIPANT_TWO_ID);

--changeset chat:001-4-chat-conversation-unique-constraint
ALTER TABLE CHAT_CONVERSATION ADD CONSTRAINT UK_CHAT_CONV_PARTICIPANTS UNIQUE (TENANT_ID, PARTICIPANT_ONE_ID, PARTICIPANT_TWO_ID);
--rollback ALTER TABLE CHAT_CONVERSATION DROP INDEX UK_CHAT_CONV_PARTICIPANTS;

--changeset chat:001-5-create-chat-message-table
CREATE TABLE IF NOT EXISTS CHAT_MESSAGE (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    CONVERSATION_ID BIGINT NOT NULL,
    SENDER_ID BIGINT NOT NULL,
    TEXT TEXT NOT NULL,
    READ_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CHAT_MSG_CONVERSATION FOREIGN KEY (CONVERSATION_ID) REFERENCES CHAT_CONVERSATION (ID),
    CONSTRAINT FK_CHAT_MSG_SENDER FOREIGN KEY (SENDER_ID) REFERENCES CHAT_USER (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_CHAT_MSG_CONVERSATION ON CHAT_MESSAGE (CONVERSATION_ID);
CREATE INDEX IDX_CHAT_MSG_SENDER ON CHAT_MESSAGE (SENDER_ID);
CREATE INDEX IDX_CHAT_MSG_CREATED_AT ON CHAT_MESSAGE (CREATED_AT);
