--liquibase formatted sql

--changeset chat:004-1-create-chat-channel-table
CREATE TABLE IF NOT EXISTS CHAT_CHANNEL (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    NAME VARCHAR(100) NULL,
    SLUG VARCHAR(100) NULL,
    DESCRIPTION VARCHAR(500) NULL,
    AVATAR_URL VARCHAR(500) NULL,
    CREATOR_ID BIGINT NOT NULL,
    IS_ARCHIVED TINYINT DEFAULT 0,
    LAST_MESSAGE_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CHAT_CHANNEL_CREATOR FOREIGN KEY (CREATOR_ID) REFERENCES CHAT_USER (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_CHAT_CHANNEL_TENANT ON CHAT_CHANNEL (TENANT_ID);
CREATE INDEX IDX_CHAT_CHANNEL_TYPE ON CHAT_CHANNEL (TYPE);
CREATE INDEX IDX_CHAT_CHANNEL_CREATOR ON CHAT_CHANNEL (CREATOR_ID);
--rollback DROP TABLE IF EXISTS CHAT_CHANNEL;

--changeset chat:004-2-chat-channel-unique-slug
ALTER TABLE CHAT_CHANNEL ADD CONSTRAINT UK_CHAT_CHANNEL_TENANT_SLUG UNIQUE (TENANT_ID, SLUG);
--rollback ALTER TABLE CHAT_CHANNEL DROP INDEX UK_CHAT_CHANNEL_TENANT_SLUG;

--changeset chat:004-3-create-chat-channel-member-table
CREATE TABLE IF NOT EXISTS CHAT_CHANNEL_MEMBER (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    CHANNEL_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ROLE VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    LAST_READ_AT TIMESTAMP NULL,
    MUTED TINYINT DEFAULT 0,
    JOINED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CHAT_CHMEM_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES CHAT_CHANNEL (ID),
    CONSTRAINT FK_CHAT_CHMEM_USER FOREIGN KEY (USER_ID) REFERENCES CHAT_USER (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_CHAT_CHMEM_CHANNEL ON CHAT_CHANNEL_MEMBER (CHANNEL_ID);
CREATE INDEX IDX_CHAT_CHMEM_USER ON CHAT_CHANNEL_MEMBER (USER_ID);
--rollback DROP TABLE IF EXISTS CHAT_CHANNEL_MEMBER;

--changeset chat:004-4-chat-channel-member-unique
ALTER TABLE CHAT_CHANNEL_MEMBER ADD CONSTRAINT UK_CHAT_CHMEM_CHANNEL_USER UNIQUE (CHANNEL_ID, USER_ID);
--rollback ALTER TABLE CHAT_CHANNEL_MEMBER DROP INDEX UK_CHAT_CHMEM_CHANNEL_USER;

--changeset chat:004-5-create-chat-tenant-settings-table
CREATE TABLE IF NOT EXISTS CHAT_TENANT_SETTINGS (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    MESSAGE_RETENTION_DAYS INT DEFAULT 365,
    MAX_FILE_SIZE_MB INT DEFAULT 50,
    ALLOW_PUBLIC_CHANNELS TINYINT DEFAULT 1,
    ALLOW_FILE_UPLOADS TINYINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--rollback DROP TABLE IF EXISTS CHAT_TENANT_SETTINGS;

--changeset chat:004-6-chat-tenant-settings-unique
ALTER TABLE CHAT_TENANT_SETTINGS ADD CONSTRAINT UK_CHAT_TENANT_SETTINGS UNIQUE (TENANT_ID);
--rollback ALTER TABLE CHAT_TENANT_SETTINGS DROP INDEX UK_CHAT_TENANT_SETTINGS;

--changeset chat:004-7-add-channel-id-to-message
ALTER TABLE CHAT_MESSAGE ADD COLUMN CHANNEL_ID BIGINT NULL AFTER CONVERSATION_ID;
ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT FK_CHAT_MSG_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES CHAT_CHANNEL (ID);
CREATE INDEX IDX_CHAT_MSG_CHANNEL ON CHAT_MESSAGE (CHANNEL_ID);
--rollback ALTER TABLE CHAT_MESSAGE DROP FOREIGN KEY FK_CHAT_MSG_CHANNEL; ALTER TABLE CHAT_MESSAGE DROP COLUMN CHANNEL_ID;
