-- liquibase formatted sql

-- changeset chat:007-1
-- comment: Add thread support to CHAT_MESSAGE (parent message, reply count, last reply)
ALTER TABLE CHAT_MESSAGE ADD COLUMN PARENT_MESSAGE_ID BIGINT NULL;
ALTER TABLE CHAT_MESSAGE ADD COLUMN REPLY_COUNT INT NOT NULL DEFAULT 0;
ALTER TABLE CHAT_MESSAGE ADD COLUMN LAST_REPLY_AT TIMESTAMP NULL;

-- changeset chat:007-2
-- comment: Add FK for parent message (self-referential)
ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT FK_CHAT_MSG_PARENT FOREIGN KEY (PARENT_MESSAGE_ID) REFERENCES CHAT_MESSAGE (ID);
CREATE INDEX IDX_CHAT_MSG_PARENT ON CHAT_MESSAGE (PARENT_MESSAGE_ID);

-- changeset chat:007-3
-- comment: Create reactions table
CREATE TABLE IF NOT EXISTS CHAT_REACTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    EMOJI VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_REACTION_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGE (ID),
    CONSTRAINT FK_CHAT_REACTION_USER FOREIGN KEY (USER_ID) REFERENCES CHAT_USER (ID),
    CONSTRAINT UK_CHAT_REACTION_MSG_USER_EMOJI UNIQUE (MESSAGE_ID, USER_ID, EMOJI)
);

CREATE INDEX IDX_CHAT_REACTION_MESSAGE ON CHAT_REACTION (MESSAGE_ID);
CREATE INDEX IDX_CHAT_REACTION_USER ON CHAT_REACTION (USER_ID);
