-- liquibase formatted sql

-- changeset chat:008-1
-- comment: Add message type and edited_at to CHAT_MESSAGE
ALTER TABLE CHAT_MESSAGE ADD COLUMN MESSAGE_TYPE VARCHAR(20) NOT NULL DEFAULT 'TEXT';
ALTER TABLE CHAT_MESSAGE ADD COLUMN EDITED_AT TIMESTAMP NULL;

-- changeset chat:008-2
-- comment: Create mentions table
CREATE TABLE IF NOT EXISTS CHAT_MENTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE_ID BIGINT NOT NULL,
    MENTIONED_USER_ID BIGINT NULL,
    MENTION_TYPE VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_MENTION_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGE (ID),
    CONSTRAINT FK_CHAT_MENTION_USER FOREIGN KEY (MENTIONED_USER_ID) REFERENCES CHAT_USER (ID)
);

CREATE INDEX IDX_CHAT_MENTION_MESSAGE ON CHAT_MENTION (MESSAGE_ID);
CREATE INDEX IDX_CHAT_MENTION_USER ON CHAT_MENTION (MENTIONED_USER_ID);

-- changeset chat:008-3
-- comment: Create attachments table
CREATE TABLE IF NOT EXISTS CHAT_ATTACHMENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE_ID BIGINT NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    MIME_TYPE VARCHAR(100) NOT NULL,
    STORAGE_KEY VARCHAR(500) NOT NULL,
    THUMBNAIL_URL VARCHAR(500) NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_ATTACHMENT_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGE (ID)
);

CREATE INDEX IDX_CHAT_ATTACHMENT_MESSAGE ON CHAT_ATTACHMENT (MESSAGE_ID);
