-- liquibase formatted sql

-- changeset chat:009-1 comment:Add fulltext index on CHAT_MESSAGE TEXT column for search
CREATE FULLTEXT INDEX FT_CHAT_MESSAGE_TEXT ON CHAT_MESSAGE (TEXT);

-- changeset chat:009-2 comment:Create CHAT_NOTIFICATION table
CREATE TABLE IF NOT EXISTS CHAT_NOTIFICATION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TENANT_ID VARCHAR(36) NOT NULL,
    USER_ID BIGINT NOT NULL,
    TYPE VARCHAR(30) NOT NULL,
    CHANNEL_ID BIGINT NULL,
    MESSAGE_ID BIGINT NULL,
    SENDER_ID BIGINT NULL,
    TITLE VARCHAR(255) NOT NULL,
    BODY VARCHAR(500) NULL,
    IS_READ TINYINT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_NOTIF_USER FOREIGN KEY (USER_ID) REFERENCES CHAT_USER (ID),
    CONSTRAINT FK_CHAT_NOTIF_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES CHAT_CHANNEL (ID),
    CONSTRAINT FK_CHAT_NOTIF_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGE (ID),
    CONSTRAINT FK_CHAT_NOTIF_SENDER FOREIGN KEY (SENDER_ID) REFERENCES CHAT_USER (ID)
);

CREATE INDEX IDX_CHAT_NOTIF_USER ON CHAT_NOTIFICATION (USER_ID);
CREATE INDEX IDX_CHAT_NOTIF_TENANT ON CHAT_NOTIFICATION (TENANT_ID);
CREATE INDEX IDX_CHAT_NOTIF_READ ON CHAT_NOTIFICATION (USER_ID, IS_READ);
CREATE INDEX IDX_CHAT_NOTIF_CREATED ON CHAT_NOTIFICATION (CREATED_AT);

-- changeset chat:009-3 comment:Create CHAT_USER_SETTINGS table for notification preferences
CREATE TABLE IF NOT EXISTS CHAT_USER_SETTINGS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    NOTIFY_DM TINYINT NOT NULL DEFAULT 1,
    NOTIFY_MENTION TINYINT NOT NULL DEFAULT 1,
    NOTIFY_CHANNEL_MESSAGES TINYINT NOT NULL DEFAULT 0,
    NOTIFY_SOUND TINYINT NOT NULL DEFAULT 1,
    NOTIFY_DESKTOP TINYINT NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHAT_USETTINGS_USER FOREIGN KEY (USER_ID) REFERENCES CHAT_USER (ID),
    CONSTRAINT UK_CHAT_USETTINGS_USER UNIQUE (USER_ID)
);
