--liquibase formatted sql

--changeset chat:010-1-create-livechat-visitor-table
CREATE TABLE IF NOT EXISTS CHAT_LIVECHAT_VISITOR (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    VISITOR_ID VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NULL,
    EMAIL VARCHAR(255) NULL,
    METADATA JSON NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT UK_LIVECHAT_VISITOR_TENANT_VID UNIQUE (TENANT_ID, VISITOR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_LIVECHAT_VISITOR_TENANT ON CHAT_LIVECHAT_VISITOR (TENANT_ID);
--rollback DROP TABLE IF EXISTS CHAT_LIVECHAT_VISITOR;

--changeset chat:010-2-create-livechat-session-table
CREATE TABLE IF NOT EXISTS CHAT_LIVECHAT_SESSION (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    SESSION_TOKEN VARCHAR(64) NOT NULL,
    VISITOR_ID BIGINT NOT NULL,
    ASSIGNED_AGENT_ID BIGINT NULL,
    QUEUE_ID VARCHAR(100) NULL,
    SOURCE_SERVICE VARCHAR(50) NOT NULL DEFAULT 'HELPDESK',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'WAITING',
    PAGE_URL VARCHAR(500) NULL,
    VISITOR_IP VARCHAR(45) NULL,
    USER_AGENT VARCHAR(500) NULL,
    MESSAGE_COUNT INT NOT NULL DEFAULT 0,
    RATING INT NULL,
    FEEDBACK TEXT NULL,
    AGENT_JOINED_AT TIMESTAMP NULL,
    CLOSED_AT TIMESTAMP NULL,
    LAST_ACTIVITY_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT UK_LIVECHAT_SESSION_TOKEN UNIQUE (SESSION_TOKEN),
    CONSTRAINT FK_LIVECHAT_SESSION_VISITOR FOREIGN KEY (VISITOR_ID) REFERENCES CHAT_LIVECHAT_VISITOR (ID),
    CONSTRAINT FK_LIVECHAT_SESSION_AGENT FOREIGN KEY (ASSIGNED_AGENT_ID) REFERENCES CHAT_USER (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_LIVECHAT_SESSION_TENANT ON CHAT_LIVECHAT_SESSION (TENANT_ID);
CREATE INDEX IDX_LIVECHAT_SESSION_TOKEN ON CHAT_LIVECHAT_SESSION (SESSION_TOKEN);
CREATE INDEX IDX_LIVECHAT_SESSION_VISITOR ON CHAT_LIVECHAT_SESSION (VISITOR_ID);
CREATE INDEX IDX_LIVECHAT_SESSION_AGENT ON CHAT_LIVECHAT_SESSION (ASSIGNED_AGENT_ID);
CREATE INDEX IDX_LIVECHAT_SESSION_STATUS ON CHAT_LIVECHAT_SESSION (STATUS);
CREATE INDEX IDX_LIVECHAT_SESSION_TENANT_STATUS ON CHAT_LIVECHAT_SESSION (TENANT_ID, STATUS);
--rollback DROP TABLE IF EXISTS CHAT_LIVECHAT_SESSION;

--changeset chat:010-3-create-livechat-message-table
CREATE TABLE IF NOT EXISTS CHAT_LIVECHAT_MESSAGE (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    SESSION_ID BIGINT NOT NULL,
    SENDER_TYPE VARCHAR(20) NOT NULL,
    SENDER_ID BIGINT NULL,
    CONTENT TEXT NOT NULL,
    MESSAGE_TYPE VARCHAR(20) NOT NULL DEFAULT 'TEXT',
    ATTACHMENT_URL VARCHAR(500) NULL,
    ATTACHMENT_NAME VARCHAR(255) NULL,
    IS_READ TINYINT NOT NULL DEFAULT 0,
    READ_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_LIVECHAT_MSG_SESSION FOREIGN KEY (SESSION_ID) REFERENCES CHAT_LIVECHAT_SESSION (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_LIVECHAT_MSG_SESSION ON CHAT_LIVECHAT_MESSAGE (SESSION_ID);
CREATE INDEX IDX_LIVECHAT_MSG_SESSION_CREATED ON CHAT_LIVECHAT_MESSAGE (SESSION_ID, CREATED_AT);
CREATE INDEX IDX_LIVECHAT_MSG_SENDER_TYPE ON CHAT_LIVECHAT_MESSAGE (SENDER_TYPE);
--rollback DROP TABLE IF EXISTS CHAT_LIVECHAT_MESSAGE;

--changeset chat:010-4-create-livechat-widget-config-table
CREATE TABLE IF NOT EXISTS CHAT_LIVECHAT_WIDGET_CONFIG (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    TENANT_ID VARCHAR(36) NOT NULL,
    ENABLED TINYINT NOT NULL DEFAULT 1,
    PRIMARY_COLOR VARCHAR(7) DEFAULT '#4F46E5',
    HEADER_TEXT VARCHAR(100) DEFAULT 'Chat with us',
    WELCOME_MESSAGE VARCHAR(500) DEFAULT 'Hello! How can we help you?',
    OFFLINE_MESSAGE VARCHAR(500) DEFAULT 'We are currently offline. Please leave a message.',
    POSITION VARCHAR(20) DEFAULT 'BOTTOM_RIGHT',
    REQUIRE_EMAIL TINYINT NOT NULL DEFAULT 0,
    AUTO_OPEN_DELAY_SECONDS INT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT UK_LIVECHAT_WIDGET_TENANT UNIQUE (TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--rollback DROP TABLE IF EXISTS CHAT_LIVECHAT_WIDGET_CONFIG;
