--liquibase formatted sql

--changeset chat:011-1-add-source-service-to-widget-config
ALTER TABLE CHAT_LIVECHAT_WIDGET_CONFIG
    ADD COLUMN SOURCE_SERVICE VARCHAR(50) NULL AFTER TENANT_ID;

-- Drop old unique constraint on TENANT_ID only
ALTER TABLE CHAT_LIVECHAT_WIDGET_CONFIG
    DROP INDEX UK_LIVECHAT_WIDGET_TENANT;

-- Add new unique constraint on (TENANT_ID, SOURCE_SERVICE)
-- NULL SOURCE_SERVICE means default/fallback config for the tenant
ALTER TABLE CHAT_LIVECHAT_WIDGET_CONFIG
    ADD CONSTRAINT UK_LIVECHAT_WIDGET_TENANT_SOURCE UNIQUE (TENANT_ID, SOURCE_SERVICE);

CREATE INDEX IDX_LIVECHAT_WIDGET_TENANT ON CHAT_LIVECHAT_WIDGET_CONFIG (TENANT_ID);
--rollback ALTER TABLE CHAT_LIVECHAT_WIDGET_CONFIG DROP INDEX IDX_LIVECHAT_WIDGET_TENANT; ALTER TABLE CHAT_LIVECHAT_WIDGET_CONFIG DROP INDEX UK_LIVECHAT_WIDGET_TENANT_SOURCE; ALTER TABLE CHAT_LIVECHAT_WIDGET_CONFIG ADD CONSTRAINT UK_LIVECHAT_WIDGET_TENANT UNIQUE (TENANT_ID); ALTER TABLE CHAT_LIVECHAT_WIDGET_CONFIG DROP COLUMN SOURCE_SERVICE;
