--liquibase formatted sql

--changeset chat-service:012-1
ALTER TABLE CHAT_LIVECHAT_SESSION
    ADD COLUMN EXTERNAL_CONTACT_PHONE VARCHAR(20) NULL,
    ADD COLUMN EXTERNAL_CONTACT_EMAIL VARCHAR(255) NULL,
    ADD COLUMN EXTERNAL_CONTACT_NAME VARCHAR(255) NULL,
    ADD COLUMN EXTERNAL_CHANNEL VARCHAR(20) NULL DEFAULT 'LIVECHAT',
    ADD COLUMN EXTERNAL_CONVERSATION_ID BIGINT NULL;

--changeset chat-service:012-2
CREATE INDEX IDX_LIVECHAT_SESSION_EXT_PHONE ON CHAT_LIVECHAT_SESSION (TENANT_ID, EXTERNAL_CONTACT_PHONE, STATUS);
CREATE INDEX IDX_LIVECHAT_SESSION_EXT_EMAIL ON CHAT_LIVECHAT_SESSION (TENANT_ID, EXTERNAL_CONTACT_EMAIL, STATUS);
