--liquibase formatted sql

-- ============================================================================
-- TENANT SERVICE - Core Tables (TNT_CORE_*)
-- ============================================================================

-- ===========================================================================
-- TNT_CORE_TENANTS
-- ===========================================================================

--changeset tenant:schema-core-tenants
CREATE TABLE IF NOT EXISTS TNT_CORE_TENANTS (
    ID CHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SLUG VARCHAR(255) NOT NULL,
    TENANT_TYPE VARCHAR(20) NOT NULL DEFAULT 'CLIENT',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    SUBSCRIPTION_STATUS VARCHAR(20) DEFAULT 'TRIAL',
    PARENT_TENANT_ID CHAR(36),
    IS_OWNER TINYINT(1) DEFAULT 0,
    BILLING_MODEL VARCHAR(20) DEFAULT 'DIRECT',
    COMMISSION_RATE DECIMAL(5,2) DEFAULT 0.00,
    WHOLESALE_DISCOUNT DECIMAL(5,2) DEFAULT 0.00,
    FINANCE_WALLET_ID CHAR(36) NULL,
    KANBAN_BOARD_ID CHAR(36) NULL,
    PROVISIONING_STATUS VARCHAR(50) DEFAULT 'COMPLETE',
    TRIAL_ENDS_AT TIMESTAMP(6),
    SUSPENDED_AT TIMESTAMP(6),
    SUSPENSION_REASON VARCHAR(500),
    CREATED_BY CHAR(36),
    DELETED_AT TIMESTAMP(6),
    DELETED_BY CHAR(36),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TNT_CORE_TENANTS_SLUG (SLUG),
    INDEX IDX_TNT_CORE_TENANTS_PARENT (PARENT_TENANT_ID),
    INDEX IDX_TNT_CORE_TENANTS_TYPE (TENANT_TYPE),
    INDEX IDX_TNT_CORE_TENANTS_STATUS (STATUS),
    CONSTRAINT FK_TNT_CORE_TENANTS_PARENT FOREIGN KEY (PARENT_TENANT_ID) REFERENCES TNT_CORE_TENANTS(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===========================================================================
-- TNT_CORE_CUSTOMERS
-- ===========================================================================

--changeset tenant:schema-core-customers
CREATE TABLE IF NOT EXISTS TNT_CORE_CUSTOMERS (
    ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NULL,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    COMPANY VARCHAR(255),
    COUNTRY_NAME VARCHAR(100),
    COUNTRY_CODE VARCHAR(10),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    WEBSITE VARCHAR(500),
    BIO TEXT,
    AVATAR VARCHAR(500),
    NICKNAME VARCHAR(100),
    JOIN_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'new',
    ACTIVITY INT DEFAULT 0,
    BALANCE DECIMAL(15,2),
    VERIFIED TINYINT(1) DEFAULT 0,
    AMOUNT DECIMAL(15,2),
    PRICE DECIMAL(15,2),
    RATING INT,
    IMAGE VARCHAR(500),
    REPRESENTATIVE_NAME VARCHAR(255),
    REPRESENTATIVE_IMAGE VARCHAR(500),
    TENANT_ID CHAR(36),
    EXTERNAL_ID VARCHAR(255),
    KIND VARCHAR(50),
    METADATA TEXT,
    PHONE VARCHAR(50),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_TNT_CORE_CUSTOMERS_TENANT (TENANT_ID),
    INDEX IDX_TNT_CORE_CUSTOMERS_STATUS (STATUS),
    INDEX IDX_TNT_CORE_CUSTOMERS_EMAIL (EMAIL),
    INDEX IDX_CUSTOMERS_USER (USER_ID),
    UNIQUE KEY UK_CUSTOMERS_TENANT_USER (TENANT_ID, USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===========================================================================
-- TNT_CORE_ENTITLEMENTS
-- ===========================================================================

--changeset tenant:schema-core-entitlements
CREATE TABLE IF NOT EXISTS TNT_CORE_ENTITLEMENTS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36),
    PRODUCT_ID CHAR(36),
    FEATURE_CODE VARCHAR(255),
    SOURCE VARCHAR(50),
    ENABLED TINYINT(1) DEFAULT 1,
    LIMIT_VALUE INT,
    EXPIRES_AT TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_TNT_CORE_ENTITLEMENTS_TENANT_PRODUCT (TENANT_ID, PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===========================================================================
-- TNT_CORE_SUPPLIERS
-- ===========================================================================

--changeset tenant:schema-core-suppliers
CREATE TABLE IF NOT EXISTS TNT_CORE_SUPPLIERS (
    ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    PHONE VARCHAR(50),
    DOCUMENT VARCHAR(50),
    CATEGORY VARCHAR(50),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    NOTES TEXT,
    ACTIVE TINYINT(1) DEFAULT 1,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    INDEX IDX_TNT_CORE_SUPPLIERS_TENANT (TENANT_ID),
    INDEX IDX_TNT_CORE_SUPPLIERS_CATEGORY (CATEGORY),
    INDEX IDX_TNT_CORE_SUPPLIERS_DOCUMENT (DOCUMENT),
    INDEX IDX_TNT_CORE_SUPPLIERS_ACTIVE (TENANT_ID, ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
