--liquibase formatted sql

-- ============================================================================
-- TENANT SERVICE - Membership Tables (TNT_ACC_*)
-- Migrated from user-service USR_MEMBERSHIPS / USR_MEMBERSHIP_ROLES
-- ============================================================================

--changeset tenant:schema-acc-memberships
CREATE TABLE IF NOT EXISTS TNT_ACC_MEMBERSHIPS (
    ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    TENANT_ID CHAR(36) NOT NULL,
    STATUS VARCHAR(255) DEFAULT 'ACTIVE',
    IS_OWNER TINYINT(1) DEFAULT 0,
    DELETED_AT TIMESTAMP(6),
    DELETED_BY CHAR(36),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    UNIQUE INDEX IDX_TNT_ACC_MEMBERSHIPS_USER_TENANT (USER_ID, TENANT_ID),
    INDEX IDX_TNT_ACC_MEMBERSHIPS_TENANT (TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset tenant:schema-acc-membership-roles
CREATE TABLE IF NOT EXISTS TNT_ACC_MEMBERSHIP_ROLES (
    MEMBERSHIP_ID CHAR(36) NOT NULL,
    ROLE_ID CHAR(36) NOT NULL,
    PRIMARY KEY (MEMBERSHIP_ID, ROLE_ID),
    CONSTRAINT FK_TNT_ACC_MR_MEMBERSHIP FOREIGN KEY (MEMBERSHIP_ID)
        REFERENCES TNT_ACC_MEMBERSHIPS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--changeset tenant:data-migrate-memberships
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:1 SELECT COUNT(*) > 0 FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'USR_MEMBERSHIPS'
INSERT IGNORE INTO TNT_ACC_MEMBERSHIPS
    (ID, USER_ID, TENANT_ID, STATUS, IS_OWNER, DELETED_AT, DELETED_BY, CREATED_AT, UPDATED_AT)
SELECT ID, USER_ID, TENANT_ID, STATUS, IS_OWNER, DELETED_AT, DELETED_BY, CREATED_AT, UPDATED_AT
FROM USR_MEMBERSHIPS;

--changeset tenant:data-migrate-membership-roles
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:1 SELECT COUNT(*) > 0 FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'USR_MEMBERSHIP_ROLES'
INSERT IGNORE INTO TNT_ACC_MEMBERSHIP_ROLES (MEMBERSHIP_ID, ROLE_ID)
SELECT MEMBERSHIP_ID, ROLE_ID FROM USR_MEMBERSHIP_ROLES;
